### ISSUE TITLE
what limitations will developers face when working with raspberry pi boards?

### ISSUE THREAD

**Issue by Mahdad-Baghani** [MicrosoftDocs/windows-iotcore-docs#1036]
Hi there, 
I think there should be more explanation about the limitations of raspberry pi. Are you referring to innate limitations of raspberry pi hardware or are there incompatibilities between raspberry pi platform and Windows IoT Core (ex. if some important features of IoT core do not work on raspberry pi boards)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257dc32b-f302-db2a-2571-8f217007d893
* Version Independent ID: 92b2f238-f621-3feb-5b5b-07aed095b115
* Content: [Suggested Prototype Boards - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/tutorials/quickstarter/prototypeboards)
* Content Source: [windows-iotcore/tutorials/quickstarter/PrototypeBoards.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/quickstarter/PrototypeBoards.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @Mahdad-Baghani, our release notes provide more details about limitations and issues. We've added a note about that in the doc you referenced.

Release notes: https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17744
