### ISSUE TITLE
Pairing is OK but no Level 4 connection established.

### ISSUE THREAD

**Issue by gmgallo** [MicrosoftDocs/windows-iotcore-docs#1041]
Running the latest version of the WiFi Direct demo (windows 10 1809 &lt;-&gt; Windows IoT Core 10.0.17763.1) the pairing succeeds and connection Level 2 is achieved, but StreamSocket.ConnectAsync() times out with a long error message which in summary says that the remote pier failed to respond. A break point on the connection request event handler of the advertiser is never triggered. StreamSocket seems to be blocked to talk to the outside world. That is by design in UWP, correct?, how to allow it to communicate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1ef6b3-6d6e-465e-a542-6d6aeddd4fea
* Version Independent ID: c49e4c94-5bfb-43a3-42e6-12e00f299a3d
* Content: [Using WiFi Direct on your Windows 10 Iot Core Device - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/setupwifidirect)
* Content Source: [windows-iotcore/connect-your-device/SetupWifiDirect.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/connect-your-device/SetupWifiDirect.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @gmgallo I've passed this onto the dev team. Stay tuned.

**Comment by gmgallo** [comment]
Hi Saraclay, meantime I found the issue. The sample project is missing Internet (Client & Server) capability checked. It has Internet (client) only, so the server never received the request. I'll implement Wifi Direct in my application now. I'll report any other issue I found.
