### ISSUE TITLE
Windows IoT dashboard is blocked 

### ISSUE THREAD

**Issue by hamedtaha** [MicrosoftDocs/windows-iotcore-docs#1048]
Does any boday have this issue white installing IoT core dashboard ?
![2019-01-27](https://user-images.githubusercontent.com/555291/51793834-b29b9b80-21cf-11e9-9813-8cf24e935b51.png)

**Comment by sadranyi** [comment]
yes I am having the same issue

**Comment by Kick4U2** [comment]
https://www.gonnalearn.com/your-administrator-has-blocked-this-application-because-it-potentially-poses-a-security-risk-to-your-computer/
