### ISSUE TITLE
support on small module board?

### ISSUE THREAD

**Issue by ariston1983** [MicrosoftDocs/windows-iotcore-docs#1053]
it's been so long that windows iot lack support on small module, almost all boards are SBC platform, full USB, LAN, HDMI ports which suit to replace computer not iot module. wish that windows iot could support small module such pi zero, compact os to replace the full linux os that run on the module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257dc32b-f302-db2a-2571-8f217007d893
* Version Independent ID: 92b2f238-f621-3feb-5b5b-07aed095b115
* Content: [Suggested Prototype Boards - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/tutorials/quickstarter/prototypeboards)
* Content Source: [windows-iotcore/tutorials/quickstarter/PrototypeBoards.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/quickstarter/PrototypeBoards.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
@ariston1983 Just out of curiosity, what would a small module board help you do that the boards we suggest don't accomplish?
