### ISSUE TITLE
Insider Preview - 18xxx releases

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/windows-iotcore-docs#1083]
Hi

Is there any news on IoT 18xxx releases?  It would be good to get a new release with full support for the Raspberry Pi 3B+.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560c6386-43f3-d102-d4d8-31a1a37f4c04
* Version Independent ID: 0f8e49e6-9f9f-301c-d261-0546e9d15ec9
* Content: [Release Notes for Build 17744 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/currentinsider)
* Content Source: [windows-iotcore/release-notes/CurrentInsider.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/CurrentInsider.md)
* Product: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshanf**

**Comment by saraclay** [comment]
Hi @pilcherd - there will be a new release of the RPi3 B+ in spring. As for 18xx releases, the most recent release of Windows 10 IoT Core was our LTSC, or long-term servicing channel, release.
