### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by mgrontzki** [MicrosoftDocs/windows-iotcore-docs#1097]
I want to send temperature values with amqp_ws to the Azure Iot-Hub. In my private Network all works fine, but my client has a protected network and all traffic must be send over the proxy server.
I'm using a Raspberry 3B with Windows 10 Iot Core (10.0.17763.107)
How can I config the proxy settings? 
- In my code?
- In the Dashboard?
- With PowerShell?
I have no Idea. 

Thanks for help.

**Comment by saraclay** [comment]
@mgrontzki you might want to file this bug under this repo: https://github.com/Azure/azure-iot-sdk-csharp/issues/

**Comment by mgrontzki** [comment]
I changed the repo. Thanks
