### ISSUE TITLE
Default audio recording device issue with .316 build

### ISSUE THREAD

**Issue by endyb66** [MicrosoftDocs/windows-iotcore-docs#1118]
I've found issue when upgrading to the latest .316 build. The default audio recording device (usb micropfone) was reset to the default one on a Dragonboard 410c.

**Comment by saraclay** [comment]
@endyb66, could you file this to your feedback hub, follow the steps [here](https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT)? That way we can get this bug triaged. Thank you for your help!
