### ISSUE TITLE
Does it wrong that I set the AllowEmbeddedMode to "Yes" on the Windows IoT Core?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-iotcore-docs#1131]
Hi,
The doc [here](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/embeddedmode) says "Embedded mode is always enabled on Window IoT Core. Embedded mode must be enabled by following the steps below on Windows IoT Enterprise."
1. Does this means that the Embedded mode is always enabled on Windows IoT Core even I didn't set the AlloEmbeddedMode to "Yes"?
2. What happened if I set the AllowEmbeddedMode to "Yes" on Windows Iot Core? Is it right or wrong? I want to always set this to "Yes" because this strategy may be changed in the future.
3. How to confirm that the Embedded mode is enabled or not on the Windows Iot Core? Is there command can do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c2bf9d-6b31-6748-90ac-68f1f472e3ff
* Version Independent ID: f305b967-06d9-cdc7-5a1c-a699485b9bc7
* Content: [Embedded mode - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/EmbeddedMode)
* Content Source: [windows-iotcore/develop-your-app/EmbeddedMode.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/EmbeddedMode.md)
* Product: **windows-iot**
* GitHub Login: @lilyhou
* Microsoft Alias: **lihou**

**Comment by saraclay** [comment]
Hi @moyanming let me ask a member of our team and will get back to you.

**Comment by saraclay** [comment]
Here are the answers:

1. Yes
2. It can't be disabled on IoT Core.
3. It always is.

**Comment by moyanming** [comment]
Hi @saraclay ,
Thank you for your answers.
