### ISSUE TITLE
The link of the "Windows.Media.SpeechSynthesis.SpeechSynthesizer" is wrong

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-iotcore-docs#1132]
Hi,
The link of the "[Windows.Media.SpeechSynthesis.SpeechSynthesizer](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/multilang#changing-user-preferences-language-region-speech-and-voice)" should be [here](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3038f54-9716-c796-b690-ceee019ac5ca
* Version Independent ID: f9c8f629-d638-5198-b379-bb39a09d00f5
* Content: [Windows 10 IoT Core Language Support - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/multilang)
* Content Source: [windows-iotcore/develop-your-app/MultiLang.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/MultiLang.md)
* Product: **windows-iot**
* GitHub Login: @msalehmsft
* Microsoft Alias: **msaleh**

**Comment by saraclay** [comment]
Good catch @moyanming - I just put in a fix. Thanks!
