### ISSUE TITLE
I can't find the Started instructions link  in this page.

### ISSUE THREAD

**Issue by onlinepy** [MicrosoftDocs/windows-iotcore-docs#1146]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5302a6a5-9017-4475-25ee-167a9b816d31
* Version Independent ID: f0bff1be-a4fe-3de0-1ea9-7ec77def3b0c
* Content: [Driver Deployment - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/driverdeployment)
* Content Source: [windows-iotcore/learn-about-hardware/DriverDeployment.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/DriverDeployment.md)
* Product: **windows-iot**
* GitHub Login: @parameshbabu
* Microsoft Alias: **pabab**

**Comment by saraclay** [comment]
Fixed this, thanks!
