### ISSUE TITLE
Please update this compatibility page

### ISSUE THREAD

**Issue by bmwzpower** [MicrosoftDocs/windows-iotcore-docs#1147]
It still indicates 'Coming soon' for iMX SoCs, I think there's broader available support now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ba1eee-09fb-7d36-e63b-578182651a95
* Version Independent ID: 426002dc-e913-bdd0-60a1-651c28f5c545
* Content: [SoCs and Custom Boards for Windows 10 IoT Core - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/socsandcustomboards#feedback)
* Content Source: [windows-iotcore/learn-about-hardware/SoCsAndCustomBoards.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/SoCsAndCustomBoards.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Yup - I'll remove that "Coming soon". Thank you!
