### ISSUE TITLE
Update sales person for PHYTEC hardware

### ISSUE THREAD

**Issue by SHeinrich85** [MicrosoftDocs/windows-iotcore-docs#1150]
Hi, Thanks for including us in your list. I'm unsure how to reach out to you to update content information. Could you update the contact person for PHYTEC to Fernando Benitez? The email remains the same. Also our new product URL is: https://phytec.com/product/phyboard-imx7-development-kit/. Thank you! Stephanie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4d6e05-f8df-a488-fc72-7f82c76d3aa8
* Version Independent ID: ee0f51b8-6699-2616-e961-9d32815a6330
* Content: [Windows IoT and NXP i.MX - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/iotnxp#feedback)
* Content Source: [windows-iotcore/learn-about-hardware/iotnxp.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/iotnxp.md)
* Product: **windows-iot**
* GitHub Login: @chsha
* Microsoft Alias: **chsha**

**Comment by saraclay** [comment]
We've created a PR for this. Thank you!
