### ISSUE TITLE
First two images on this document page are not visible

### ISSUE THREAD

**Issue by StefH** [MicrosoftDocs/windows-iotcore-docs#1159]
![Add a feature](../media/SSH/add_a_feature.png)

![OpenSSH Client Install](../media/SSH/optional_features.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf58bd4-6564-f62a-726e-f9b3d306d7ba
* Version Independent ID: 7adc4b6d-24cc-a0bc-f720-ebaef9c6620e
* Content: [Secure Shell (SSH) - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/SSH)
* Content Source: [windows-iotcore/connect-your-device/SSH.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/connect-your-device/SSH.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
This has been fixed and changes should propagate soon. Thank you!
