### ISSUE TITLE
I think, as of RS5 that IoT Enterprise supports ARM64

### ISSUE THREAD

**Issue by ksaye** [MicrosoftDocs/windows-iotcore-docs#1174]
We need to update our documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f088c6-a9fc-a115-681c-b2f1621e2320
* Version Independent ID: 72ce0d63-d6e2-b5d3-926f-b3df60526ddc
* Content: [Overview of Windows 10 IoT Enterprise - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/windowsiotenterprise#differences-between-windows-10-iot-core-and-windows-10-iot-enterprise)
* Content Source: [windows-iotcore/learn-about-hardware/WindowsIoTEnterprise.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/WindowsIoTEnterprise.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Sorry, could you be more specific? @ksaye
