### ISSUE TITLE
nslookup.exe command doesn't work for Windows 10 IoT core for Raspberry

### ISSUE THREAD

**Issue by VitorX** [MicrosoftDocs/windows-iotcore-docs#1177]
nslookup.exe command doesn't work for Windows 10 IoT core for Raspberry.
OS version: 10.0.17763.379

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d73c19-8da8-ed8b-72fb-c19dcdb1b756
* Version Independent ID: 3f136a06-a924-abca-b5fb-650d6dd46dec
* Content: [Windows 10 IoT Core Command Line Utilities - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/commandlineutils)
* Content Source: [windows-iotcore/manage-your-device/CommandLineUtils.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/manage-your-device/CommandLineUtils.md)
* Product: **windows-iot**
* Technology: **iot**
* GitHub Login: @bfjelds
* Microsoft Alias: **bfjelds**

**Comment by saraclay** [comment]
@VitorX We're looking into this.
