### ISSUE TITLE
Iot Dashboard how to flash custom ffu image

### ISSUE THREAD

**Issue by trivalik** [MicrosoftDocs/windows-iotcore-docs#1180]
The page https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/create-a-basic-image states that device type provide "custom" point. But there 
![device type](https://user-images.githubusercontent.com/3148279/55216411-f4ab8280-51fc-11e9-8099-8795d629c7ea.png)
is no such, see attached.

**Comment by trivalik** [comment]
Maybe is the documentation just out dated.
Custom is in combo box "OS build".

**Comment by saraclay** [comment]
You are correct, @trivalik - the Dashboard currently does offer a "Custom" option.

**Comment by trivalik** [comment]
Are you intent to change the page?
