### ISSUE TITLE
Wrong interface for MCP23S17

### ISSUE THREAD

**Issue by newbrain** [MicrosoftDocs/windows-iotcore-docs#1205]
MCP23S17 16-bit I/O Port Expander is wrongly reported as I2C, it actually is SPI.
The entry is then ambiguous: is the 23S17 supported on SPI or the 23017 on I2C or both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8da9d0-10ee-b8e6-6c11-16f1faf8a630
* Version Independent ID: e45ebd71-6334-7dd6-87a2-933210996f4c
* Content: [Hardware Compatbility List - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist#feedback)
* Content Source: [windows-iotcore/learn-about-hardware/HardwareCompatList.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/HardwareCompatList.md)
* Product: **windows-iot**
* Technology: **iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
It is SPI. Thanks for pointing this out.
