### ISSUE TITLE
Incorrect list index and Powshell script format

### ISSUE THREAD

**Issue by v-liujxu** [MicrosoftDocs/windows-iotcore-docs#1213]
In **Generate Lockdown Packages** section, the index of 'Execute the following commands to generate required packages:' should be 7 in the numbered list. And more, the format powershell script is incorrect.

**Comment by saraclay** [comment]
@v-liujxu do you mind including the link to the documentation you're referring to? Thank you!

**Comment by v-liujxu** [comment]
@saraclay , here is the document link.
[https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/securebootandbitlocker](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/securebootandbitlocker)

**Comment by saraclay** [comment]
Thank you. We're in the process of updating this doc, as well as a few others. We'll see if this issue is fixed in the update.
