### ISSUE TITLE
"this list"-link from "Getting started" section leads to this same page

### ISSUE THREAD

**Issue by Arminator** [MicrosoftDocs/windows-iotcore-docs#1227]
"Getting started" mentions a list of vendors to contact to start manufacturing with Win 10 IoT Enterprise. Howver the "this list" link only links to this same page, instead of a list with vendors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1e7dc7e-3df6-2eaf-9c11-ed03c00719e0
* Version Independent ID: ab5e43cf-c4db-cd8f-e92a-c33e4ebc2b68
* Content: [Overview of Windows 10 IoT Enterprise - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise)
* Content Source: [windows-iotcore/windows-iot-enterprise.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/windows-iot-enterprise.md)
* Product: **windows-iot**
* Technology: **iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Yikes, thank you for catching this. I'm making changes now.
