### ISSUE TITLE
Is Windows 10 IoT Enterprise 2019 LTSC released?

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/windows-iotcore-docs#1232]
In this document is the future used for the LTSC release:
> The Fall 2018 release of Windows 10 IoT Enterprise will also be an LTSC release. 

Windows 10 Enterprise LTSC 2019 is released: https://docs.microsoft.com/en-us/windows/whats-new/ltsc/#the-long-term-servicing-channel-ltsc
Is Windows 10 __IoT__ Enterprise 2019 LTSC also released and this documentation not updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1e7dc7e-3df6-2eaf-9c11-ed03c00719e0
* Version Independent ID: ab5e43cf-c4db-cd8f-e92a-c33e4ebc2b68
* Content: [Overview of Windows 10 IoT Enterprise - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise)
* Content Source: [windows-iotcore/windows-iot-enterprise.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/windows-iot-enterprise.md)
* Product: **windows-iot**
* Technology: **iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
You are correct. I've just updated this. Thank you for filing an issue!
