### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by klang-uofi** [MicrosoftDocs/windows-iotcore-docs#1239]
It looks like the distributor list under "Getting Started" (https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise#getting-started) just links back to the current page (https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise). I'm guessing it's just missing an anchor, but I'm not sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1e7dc7e-3df6-2eaf-9c11-ed03c00719e0
* Version Independent ID: ab5e43cf-c4db-cd8f-e92a-c33e4ebc2b68
* Content: [Overview of Windows 10 IoT Enterprise - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise#feedback)
* Content Source: [windows-iotcore/windows-iot-enterprise.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/windows-iot-enterprise.md)
* Product: **windows-iot**
* Technology: **iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
This has been fixed. Sorry for the confusion!
