### ISSUE TITLE
AllJoyn is no longer supported by Windows 10 IoT

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/windows-iotcore-docs#1269]
AllJoyn is no longer supported by Windows 10 IoT. Any Better choice for Service discovery in IOT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150231f8-c244-73ee-7703-71851fe88c95
* Version Independent ID: c162f11b-c7a9-476e-825a-6ab10db40c4f
* Content: [AllJoyn Overview - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/archive/alljoyn)
* Content Source: [windows-iotcore/archive/AllJoyn.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/archive/AllJoyn.md)
* Product: **windows-iot**
* Technology: **iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
@meteorsnows The app-layer IoT protocol that serves as the replacement for AllJoyn is [OCF](https://openconnectivity.org/).  The standard implementation of the OCF spec is Iotivity – Windows support for Iotivity can be found [here](https://wiki.iotivity.org/windows). Hope this helps!
