### ISSUE TITLE
Raspberry Pi 3B+ Touch screen

### ISSUE THREAD

**Issue by Owlowish** [MicrosoftDocs/windows-iotcore-docs#1324]
Hello,
I have a Raspberry 3B+ running with Winwods IoT core. I'm aware that it is still a technical preview and the that the Ft5406 touch screen driver is disabled (The display works but the touch functionality). But I want to know if there's any way to activate it. If not, will we have a version with a working touch screen in a near future ? Thanks You.

Best regards,

**Comment by TerryWarwick** [comment]
Closing due to age. If issue persists, please submit a new issue.
