### ISSUE TITLE
App Installation Instructions are badly out of date

### ISSUE THREAD

**Issue by scout208** [MicrosoftDocs/windows-iotcore-docs#1360]
The instructions on this page https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/appinstaller haven't been updated since 2017 and many things have changed since then so some of the instructions and images are no longer valid. Additionally, installing apps the ways described in this page doesn't allow you to start them if the package is a .msix file which is the only supported package version in the latest version of Visual Studio so the instructions are now obsolete.

**Comment by saraclay** [comment]
Thank you @scout208 - you're absolutely right. I will raise this internally and ask this to be prioritized.

**Comment by saraclay** [comment]
These have been updated.
