### ISSUE TITLE
hyperlink not working

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-iotcore-docs#1373]
The hyper link on Getting started > "In order to start your journey in manufacturing with Windows 10 IoT Enterprise, you'll need to reach out to a distributor from this list." isn't working

https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise

**Comment by saraclay** [comment]
Thank you @xNiklasJern - I've just put in a fix for this.
