### ISSUE TITLE
Whitepaper / information on POS scenario wanted

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-iotcore-docs#1374]
Hi,

not as much of an issue than looking for information.

The table on https://docs.microsoft.com/en-us/windows/iot-core/windows-iot i s refercing that a usage scenario for Windows 10 IoT Enterprise could be POS. 
Are there any whitepaper on a set up like this or how it has be utilized?
I'm looking for any information on how Windows 10 IoT (in a POs scenario) would work with the modern device management mindset (utilization of EMS etc...) would work.

Regards,

**Comment by saraclay** [comment]
Thank you for the suggestion, @xNiklasJern. I will pass this suggestion onto the right person on our team.
