### ISSUE TITLE
Windows 10 IoT Core Command doc need update

### ISSUE THREAD

**Issue by xuliujian2019** [MicrosoftDocs/windows-iotcore-docs#1397]
I have updated my Windows IoT Core to build 17763.503. I found out there are some new commands included in this build, such as` IotStartup run` and `IotStartup stop`. I am not sure these new features included from which build. But the [command document](https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/commandlineutils) has not been updated yet.

**Comment by saraclay** [comment]
@xuliujian2019, thank you for the recommendation. We just updated the document. Could you take a look and let us know if this is what you were looking for?
