### ISSUE TITLE
How to change the EFIESP volume GUID ?

### ISSUE THREAD

**Issue by LiangJy123** [MicrosoftDocs/windows-iotcore-docs#1444]
Hi , I want to enable the Bitlocker on  Windows 10 IoT Core.

As the document tips, "it’s necessary to ensure that the EFIESP volume GUID is set to C12A7328-F81F-11D2-BA4B-00A0C93EC93B."
![image](https://user-images.githubusercontent.com/13048899/60591910-0d19d300-9dd2-11e9-8060-21ac96259cf2.png)
But I can't find the official way to change the volume GUID .
Can you give me some suggestions?

Thanks!

Info of my project:
Hardware :  Minnowboard max
OS            :  Windows 10 IoT Core - 17763
TPM          :  fTPM Enabled

**Comment by jianminfly** [comment]
I know,but I do not want to tell you how should to do (*￣︶￣)
