### ISSUE TITLE
USBFN support in Intel Atom e3900

### ISSUE THREAD

**Issue by keshavagn** [MicrosoftDocs/windows-iotcore-docs#1460]
Hi,

Is there support for USBFN in Intel Atom e3900 BSP? If not, how to develop it? If I get steps to develop the support, it would be helpful.

Thanks,
Keshava G N

**Comment by saraclay** [comment]
[This ](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/bsphardware#intel-bsps )should help.
