### ISSUE TITLE
Details on Geolocation implementation / poor satellite performance

### ISSUE THREAD

**Issue by crates-barrels** [MicrosoftDocs/windows-iotcore-docs#1540]
Hi,

We're using the Dragonboard 410c as a base for our field gateway, but we're having problems gathering GPS data from the devices.
The board runs Windows 10 IoT Core v1809 (10.0.17763.253) and a UWP app using the _Windows.Devices.Geolocation.Geolocator_ class to obtain satellite data. However, _.GetGeopositionAsync()_ almost never returns a _Satellite_ coordinate as the position source. The resulting coordinates are almost always based on _WiFi_ or _IPAddress_, which is far too inaccurate.
That's why we only keep the coordinates coming from a satellite source and skip the rest.
The issue is further described here: https://social.msdn.microsoft.com/Forums/en-US/4163b663-c045-411f-8b64-2ed33786f0ad/dragonboard-410c-geolocation-issue-only-occasional-data-from-gnss

We are convinced our setup (and GNSS sensor) is working, because it's tested using a Linux image and a correct satellite fix is obtained between 20 seconds and 2 minutes with an external antenna.

I'm trying to investigate the issue further and pinpoint the exact cause, but then I need to get the "raw" data from the GNSS sensor. Is there documentation on how to do this somewhere? I don't know where to start, as the sensor driver does not expose a serial port (at least not in UWP).
Or is there any documentation about the details how the _Geolocator_ is working internally?

If anyone can give me pointers as to why satellite performance is so poor on Windows 10 IoT Core or ways to improve this would be greatly appreciated!

Best regards.

**Comment by TerryWarwick** [comment]
Closing due to age. If issue persists, please submit a new issue.
