### ISSUE TITLE
Does not work in raspberry pi 4

### ISSUE THREAD

**Issue by Mosheh** [MicrosoftDocs/windows-iotcore-docs#1544]
After the installation in SD and put it in raspberry pi 4 nothing happens when I start the model.
Data:
Pi 4 64-bit quad-core processor running 1.5 GHz. 
4GB RAM
SD 32 GB  Class 10

**Comment by e-leoni** [comment]
Hi @Mosheh , you can follow this discussion:
https://social.msdn.microsoft.com/Forums/office/en-US/8092f66a-2910-48dd-abd6-141c8487eec6/raspberry-pi-4-is-now-available-where-is-windows-iot?forum=WindowsIoT
We are all waiting for a new release for raspberry pi4.

**Comment by TerryWarwick** [comment]
Closing due to age. If issue persists, please submit a new issue.
