### ISSUE TITLE
New release of Windows 10 IoT Core for Raspberry Pi 3B

### ISSUE THREAD

**Issue by shanerusso** [MicrosoftDocs/windows-iotcore-docs#1551]
There have been various comments such as from @saraclay about a new release of Windows 10 IoT Core. The last release estimate mentioned was in spring (which has now passed). 

Are there any updates on when a new release will be happening?

A particular issue I have is trying to use a Proxy in a UWP on Windows 10 IoT Core. This is currently unsupported but Microsoft have advised it will be available in a future release. 

Is there any information on whether proxy will be enabled in Windows 10 IoT Core?

**Comment by TerryWarwick** [comment]
There are currently no plans for a new release of Windows 10 IoT Core.  For extended support of Windows 10 IoT Core we recommend [IoT Core Services](https://learn.microsoft.com/windows-hardware/manufacture/iot/iotcoreservicesoverview).  Future investments will be focused on Windows IoT Enterprise platform.
