### ISSUE TITLE
Difficulty with test packages

### ISSUE THREAD

**Issue by Zarshua** [MicrosoftDocs/windows-iotcore-docs#1567]
I'm trying to understand what I'm missing from this article: https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/securebootandbitlocker#turnkey-security-on-iot-core

I want to verify that the test packages are working with the test certificates before I generate a set of production keys.

I can follow all the steps in this article and the packages don't appear to work -- is there any configuration that needs to happen in the IoT Core image I build before these test packages will work?

**Comment by TerryWarwick** [comment]
Closing due to age. If issue persists, please submit a new issue.
