### ISSUE TITLE
Lightning Providers docs refer to abandoned functionality

### ISSUE THREAD

**Issue by andriysavin** [MicrosoftDocs/windows-iotcore-docs#1569]
This doc page
[https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/LightningProviders.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/LightningProviders.md) describes Lightning Providers, however the article refers to the archived repository and, looks like, abandoned functionality.    I'd like the article be updated with some kind of warning specifying the current state of Lightning Providers and that this is no longer supported.

**Comment by TerryWarwick** [comment]
The repository is still available, however it is no longer being maintained.
