### ISSUE TITLE
Problem with downloading Windows iOT

### ISSUE THREAD

**Issue by Marvin1203** [MicrosoftDocs/windows-iotcore-docs#1578]
Hey,
there is a problem with the download link for Windows iOt for the Raspberry Pi 3B+. Every time when I click on the file there is an error. 
The windows support can't help me, they only say me that the link is brocken.

**Comment by parameshbabu** [comment]
the download link is in the insider page. If you are signed up as the Windows insider, you should be able to download the image.

**Comment by Marvin1203** [comment]
Thank you, but I knew that. 
I downloaded it now from another PC and there it works.
