### ISSUE TITLE
https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/networkpacketcapture contains a dead link.

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windows-iotcore-docs#1581]
https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/networkpacketcapture contains a dead link for Microsoft Message Analyzer. In addition, Microsoft Message Analyzer no longer exists.

**Comment by TerryWarwick** [comment]
Microsoft Message Analyzer has been [deprecated](https://learn.microsoft.com/en-us/openspecs/blog/ms-winintbloglp/dd98b93c-0a75-4eb0-b92e-e760c502394f). Information in this article is for archival reference only.
