### ISSUE TITLE
About Windows IOT core for INTEL JOULE. Need help.

### ISSUE THREAD

**Issue by mopplayer** [MicrosoftDocs/windows-iotcore-docs#1611]
Hi,

Is there a ISO for INTEL JOULE.
How to download the latest ISO for **"Windows10_InsiderPreview_IoTCore_IntelJoule_ARM32ARM64_en-us_16267.iso".**

Thanks.

**Comment by chsha** [comment]
Intel discontinued the Joule product line several yeas ago - https://ark.intel.com/content/www/us/en/ark/products/series/96418/intel-joule-products.html. There is no updated ISO with the latest IoT Core OS. You may try to contact Intel to see if they have drivers which you can use to manually build a system image.

**Comment by mopplayer** [comment]
Hi,

I know the product is end of life.
But I just want to try Windows IOT core for JOULE.
Is there the latest ISO?

Thanks.

**Comment by chsha** [comment]
No. We no longer produce an ISO for Joule with the latest IoT Core OS.

**Comment by mopplayer** [comment]
Hi,

I mean 16267 version ISO.

Thanks.
