### ISSUE TITLE
Local server

### ISSUE THREAD

**Issue by ramtinak** [MicrosoftDocs/windows-iotcore-docs#163]
Hi, I find out in Windows 10 Iot for create a local server between Rspi 3 model B and other devices(like windows mobile/android devices) you have to plug the LAN cable to Rspi to work this.
Why is that?
Why Win Iot couldn't create server over connected network(WIFI)? 

P.s: In this scenario rspi is server, and other devices is clients.

**Comment by saraclay** [comment]
Hello,

The Raspberry Pi 3 should be able to work with WiFi. Sometimes, however, the connection may not be as stable as when plugged into Ethernet. That's why you might find it easier when working with Ethernet.
