### ISSUE TITLE
Playing videos

### ISSUE THREAD

**Issue by ramtinak** [MicrosoftDocs/windows-iotcore-docs#164]
Hi, Why Windows Iot couldn't play videos as well?
I couldn't play a 720p video.
I think Raspberry pi 3 model B support FHD videos.

**Comment by saraclay** [comment]
Hello,

For the future, could you please file bugs you come across using the Feedback Hub? Thank you.

Instructions can be found here: https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT
