### ISSUE TITLE
can not debug UWP app on raspberry pi 3

### ISSUE THREAD

**Issue by MarshalOfficial** [MicrosoftDocs/windows-iotcore-docs#1645]
hi there, I have a raspberry pi 3 that connected to my local network, so I can connect to that via ip:8080 in the browser, but when I want to run visual studio 2019 the last update to the raspberry, it failed with this error:
 Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP6701: Bootstrapping failed with unexpected error: Exception from HRESULT: 0x801C000B	App1			

I have searched a lot but nothing find around it.

**Comment by TerryWarwick** [comment]
Closing due to age.  If this issue persists, please engage through support as opposed to documentation
