### ISSUE TITLE
Add Supported Hardware Revisions List to Raspberry Pi page

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/windows-iotcore-docs#1653]
The current documentation is unclear about what specific versions of Raspberry Pi hardware are supported 

Given the bugs in this repo (and posts elsewhere), I assume Raspberry Pi 4 is not supported at this time, but if that's the case, it would be great if that was reflected in the documentation.

**Comment by TerryWarwick** [comment]
You assessment is accurate
