### ISSUE TITLE
404 This is not the web page you are looking for.

### ISSUE THREAD

**Issue by luizpires** [MicrosoftDocs/windows-iotcore-docs#1662]
Hello,

The "Project repository: Limpet project repository" link, which is at the bottom of the page https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/azureiotdm?source=docs, does not it's working.

To Reproduce

Go to 'https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/azureiotdm?source=docs'
Click on 'Project repository: Limpet project repository.'
See error: 404 This is not the web page you are looking for.

**Comment by TerryWarwick** [comment]
@luizpires, this issue was due to a hosting service outage.  Once restored the link was functional again
