### ISSUE TITLE
Windows IoT download resource not found

### ISSUE THREAD

**Issue by davidbichara** [MicrosoftDocs/windows-iotcore-docs#1689]
When pressing the download button on [this ](https://learn.microsoft.com/en-us/windows/iot-core/downloads)page I receive the following output in a new webpage:
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:71e3a56a-101e-0096-448c-e587b7000000 Time:2022-10-21T20:34:17.1954272Z</Message>
</Error>`

This prevents users like myself from downloading windows IoT. 

Are there any solutions for this? is this a backend problem?

**Comment by TerryWarwick** [comment]
@davidbichara, the problem you encountered was due to an issue with the hosting service.  This has been resolved.
