### ISSUE TITLE
Stuck on step 8 of Setting up an Intel device

### ISSUE THREAD

**Issue by cvalerio** [MicrosoftDocs/windows-iotcore-docs#1690]
I'm trying to follow the guide at https://learn.microsoft.com/en-us/windows/iot-core/tutorials/intel, but when I reach step 8 there is something that isn't working as described.

I've downloaded the iso from step 7 (file name: `Windows10_IoTCore_Packages_ARM32_en-us_17763_253.iso`), mounted the iso file and launched both `Windows_10_IoT_Core_X64_Packages.msi` and `Windows_10_IoT_Core_X86_Packages.msi` but no directory `C:\Program Files (x86)\Microsoft IoT\FFU\` was created on my PC.

Both the msi end stating that stuff has been put in `C:\Program Files (x86)\Windows Kits\10`, but no ffu file is in this directory either.

Any help will be greatly appreciated.

**Comment by TerryWarwick** [comment]
This may have been an issue with the hosting service that has since been restored.  Please submit a support ticket if the issue persists
