### ISSUE TITLE
MAUI support

### ISSUE THREAD

**Issue by kdotdk** [MicrosoftDocs/windows-iotcore-docs#1712]
Hi

In the [overview page](https://learn.microsoft.com/en-us/windows/iot-core/windows-iot-core#differences-between-windows-10-iot-core-and-windows-10-iot-enterprise) I read IoT Core only support UWP apps. 
Does this include MAUI or will MAUI be supported?

**Comment by TerryWarwick** [comment]
IoT Core only supports UWP apps.  IoT Core Services does not change that design.
