### ISSUE TITLE
When do approved changes show up in docs.microsoft.com

### ISSUE THREAD

**Issue by djaus2** [MicrosoftDocs/windows-iotcore-docs#246]
My changes to The IoT-Core Bluetooth page have been validated and show as such in the GitHub repository as such 
https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/connect-your-device/Bluetooth.md

but don't show on https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/bluetooth

**Comment by saraclay** [comment]
Hello,

Can you check again? They should be reflected.

**Comment by djaus2** [comment]
Ok its there.
If it was there when I previously checked it must've been a caching issue.
Thx

Ps Working on further updates to this page.

**Comment by saraclay** [comment]
It's usually a caching issue :) No worries.
