### ISSUE TITLE
RPi3 does not boot in headless mode

### ISSUE THREAD

**Issue by alexiordan** [MicrosoftDocs/windows-iotcore-docs#250]
What does it mean? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98735248-fd9a-09cb-848d-5439e6722ae4
* Version Independent ID: 91cb333b-1915-464c-18a7-cc99025e9378
* Content: [Release Notes for Build 17083 - Windows IoT | Microsoft Docs](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17110)
* Content Source: [windows-iotcore/release-notes/Insider/17110.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/Insider/17110.md)
* Service: **unspecified**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by saraclay** [comment]
Hi Alex, if you connect to a device via SSH or remote PowerShell and set the bootoption as headless, the device will hang. We currently are fixing this bug.
