### ISSUE TITLE
Visual Studio 2017 remote debugger

### ISSUE THREAD

**Issue by nphmuller** [MicrosoftDocs/windows-iotcore-docs#254]
This page only allows me to start a remote debug session from Visual Studio 2015. Is there a way to use Visual Studio 2017 instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49bd94-e4f5-da54-37b5-05e2c8556f2d
* Version Independent ID: 6987221f-5acd-c9d8-cf7d-96d6264a272a
* Content: [Debug your app using Remote Console App Debugging - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/remotedebugging)
* Content Source: [windows-iotcore/develop-your-app/RemoteDebugging.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/RemoteDebugging.md)
* Service: **unspecified**
* GitHub Login: @bfjelds
* Microsoft Alias: **brian.fjeldstad**

**Comment by bfjelds** [comment]
The Visual Studio 2017 remote debugger should work as well.  That screenshot should be updated.

**Comment by nphmuller** [comment]
Okay, thanks!
