### ISSUE TITLE
How to read and write to a GPIO Pin which is not list in the GPIO Pin Table?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-iotcore-docs#273]
How to read and write to a GPIO Pin which is not list in the GPIO Pin Table (https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/pinmappings/pinmappingsdb#gpio-pin-table)? For example, how to read and write to a GPIO#100?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf4b39be-e0ef-9db7-d542-248e8d107471
* Version Independent ID: 2862e930-3f9f-c73f-cf57-1396ceeeadc0
* Content: [Dragonboard Pin Mappings - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/pinmappings/pinmappingsdb#gpio-pin-table)
* Content Source: [windows-iotcore/learn-about-hardware/PinMappings/PinMappingsDB.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/PinMappings/PinMappingsDB.md)
* Service: **unspecified**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
@moyanming Hello, we advise that you try and work with a Microsoft partner on issues that you are facing.
