### ISSUE TITLE
Unable to Download Live Kernel Dump

### ISSUE THREAD

**Issue by scout208** [MicrosoftDocs/windows-iotcore-docs#277]
Clicking **Download live kernel dump** in the **Debug Settings** section of the Device Portal just takes me to a "This page isn't working" page on Google Chrome.

![image](https://user-images.githubusercontent.com/9426329/38634562-7a4cca96-3d88-11e8-9575-20df52564bbf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3109c64e-0fff-04f4-d572-84851f558643
* Version Independent ID: 2db48f5c-f8c6-4258-eb6f-1e0710c014f0
* Content: [Windows Device Portal - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/deviceportal#debugging)
* Content Source: [windows-iotcore/manage-your-device/DevicePortal.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/manage-your-device/DevicePortal.md)
* Service: **unspecified**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @scout208! Taking a look at this right now.

**Comment by saraclay** [comment]
We have a bug filed for this. Stay tuned - let us know if this is a blocking issue for you.

**Comment by saraclay** [comment]
Apologies @scout208 - we're still waiting to get this fixed. Please let me know if this is a blocker for you - closing this out for now.
