### ISSUE TITLE
Where is the "I2C Accelerometer" on the github?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-iotcore-docs#280]
The "SPI Accelerometer Sampler" and "I2C Acceleromenter Sample" of the "lowLevelDevice Capability" (https://docs.microsoft.com/zh-cn/windows/iot-core/develop-your-app/embeddedmode#lowleveldevice-capability) are both link to the same website after jump to the github website. They all both link to the: https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/Samples/Accelerometer. Where is the "I2C Accelerometer" on the github?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 17c2bf9d-6b31-6748-90ac-68f1f472e3ff
* Version Independent ID: f305b967-06d9-cdc7-5a1c-a699485b9bc7
* Content: [Embedded mode - Windows IoT](https://docs.microsoft.com/zh-cn/windows/iot-core/develop-your-app/embeddedmode#lowleveldevice-capability)
* Content Source: [windows-iotcore/develop-your-app/EmbeddedMode.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/EmbeddedMode.md)
* Service: **unspecified**
* GitHub Login: @lilyhou
* Microsoft Alias: **lihou**

**Comment by saraclay** [comment]
It is the same sample.
