### ISSUE TITLE
Wifi AP - Win 10 IoT core on Raspberry Pi 3 does not connect with clients

### ISSUE THREAD

**Issue by bstcoder** [MicrosoftDocs/windows-iotcore-docs#296]
By following the documentation on Internet Connection Sharing, I could get to set Raspberry Pi 3 as a Wifi AP but cannot get wifi client devices to connect to the AP. Client devices can see the SSID but does not successfully connect and is stuck at 'Obtaining IP address'.

**Comment by saraclay** [comment]
Is this a blocking issue for you? What exactly would you like to know?
