### ISSUE TITLE
How many connections can be made to the device running IoT?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/windows-iotcore-docs#302]
I'm considering replacing Windows Server based industrial PC's in a manufacturing area with Win 10 IoT devices, but they will need to communicate with (bidirectionally) other Tcp based devices (PLC's, printers, PC Servers, HMI's, browsers, etc). 

THe Windows 7 limit of 10 or 20 connections was just too few.  What are the official, non-speculative, limits for connections in IoT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1e7dc7e-3df6-2eaf-9c11-ed03c00719e0
* Version Independent ID: ab5e43cf-c4db-cd8f-e92a-c33e4ebc2b68
* Content: [Overview of Windows 10 IoT Enterprise - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise)
* Content Source: [windows-iotcore/windows-iot-enterprise.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/windows-iot-enterprise.md)
* Service: **unspecified**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @StingyJack, according to our agreement, you may allow up to 20 other devices to access the software installed on the license device.

**Comment by StingyJack** [comment]
I'm not really asking about "accessing the software installed on the device", I'm talking about connecting to an endpoint or raw socket that the device is hosting. Is there a fixed request limit where clients will start to queue up and wait?
