### ISSUE TITLE
C++ Headers or examples?

### ISSUE THREAD

**Issue by BlackDogWhite** [MicrosoftDocs/windows-iotcore-docs#307]
It would be really nice if you could supply some hints on accessing Pi hardware via C++. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525c643a-0e4f-a732-cc19-bc304acc5862
* Version Independent ID: 028d320a-4eb6-a419-4933-b64c7abdf145
* Content: [Raspberry Pi 2 & 3 Pin Mappings - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/pinmappings/pinmappingsrpi#feedback)
* Content Source: [windows-iotcore/learn-about-hardware/PinMappings/PinMappingsRPI.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/PinMappings/PinMappingsRPI.md)
* Service: **unspecified**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by LNTDS** [comment]
Not sure if this helps but there is a Serial UART example using C++: https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/Samples/SerialUART

Would be cool to have GPIO Pi example using C++.
