### ISSUE TITLE
Update Process

### ISSUE THREAD

**Issue by LNTDS** [MicrosoftDocs/windows-iotcore-docs#332]
Hey all,

I am currently attempting the "Windows Update" process on "Windows Device Portal" but IoT Core cannot find the latest April update 17134.

I am running the prior commercial release of IoT, v.10.0.16299.371, Raspberry Pi 3B and have attempted updates today, 18/05/05. Is there a delay until the update is pushed to Windows Update or is the expectation to use the "Windows 10 IoT Core Dashboard" re-flashing the microSD card?

![rasppi3winiotupdate](https://user-images.githubusercontent.com/39007383/39664116-63382e1c-5076-11e8-9ae8-d83e4b67f720.PNG)

**Comment by saraclay** [comment]
Hi @LNTDS - have you tried again? Sometimes there is a delay.

**Comment by LNTDS** [comment]
Hi @saraclay, I just checked and I received the update yesterday evening. Must be a delay for the UK 😛 Thanks!
