### ISSUE TITLE
Updates to config.txt video HDMI settings for  17661 and back to 16299 for error Status: 0xc000014c

### ISSUE THREAD

**Issue by jimshalo10** [MicrosoftDocs/windows-iotcore-docs#352]
Here is my patched config.txt which works for all versions from 16299 to Windows 10  IoT Insider build 17661
______________________________________________________________________________
#For more options and information see
#http://www.raspberrypi.org/documentation/configuration/config-txt.md
#Some settings may impact device functionality. See link above for details
#GPU Firmware SHA256 checksum: 7CE2EF13CDD77F1782FFFF98533572503DF4B46765966CC7E18F6C6455B9623A
#kernel.img SHA256 checksum: 6C82C8720BE4EFB2951BDC01FA187B0B659227033EB7D7DB5ACA6324FD644D7F
#kernel.img git commit ID: f6706f4bd3b10c8294589f45082c8bdc4c50be59
#edit this file config.txt in the drive labelled EDFI after flashing SD, 
#BEFORE installing SD Raspberry Pi 3
#The TV Set with HDMI will display the error the first time
#
#Status: 0xc000014c
#Info: An unexpected error has occurred.
#
#The first time will set up the TV/HDMI to 1920 x 1080 and hold the setting
#unplug power to RP3 board# the power up again
#the second time the screen will show the windows 10 boot 
#
#Boot
#
init_uart_clock=16000000    # Set UART clock to 16Mhz
kernel_old=1                # Load kernel.img at physical memory address 0x0
safe_mode_gpio=8            # A temp firmware limitation workaround
max_usb_current=1           # Enable maximum usb current
#
#Memory
#
gpu_mem=32                  # Set VC to 32MB, ARM DRAM to (1008-32)MB
#comment out as already has connected HDMI disable
#hdmi_force_hotplug=1        # Enable HDMI display even if it is not connected (640x480)
#
#Overclocking
#
core_freq=250               # Frequency of GPU processor core in MHz
#
#Video
#
#
framebuffer_ignore_alpha=1  # Ignore the alpha channel for Windows.
framebuffer_swap=1          # Set the frame buffer to be Windows BGR compatible.
disable_overscan=1          # Disable overscan
#Use Display Mode Timing over CEA hdmi_group=1     
hdmi_group=1               
hdmi_mode=5   # HDMI 1920 x 1080 group 1 mode 5
#switch off cvt 
#hdmi_cvt 800 480 60 6 0 0 0 # Add custom 800x480 resolution (group 2 mode 87)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c6f0a1-6699-bc0c-84e6-00e75811e2c3
* Version Independent ID: 5adec4ff-8fd6-f8d0-3437-cdde9a32a504
* Content: [Release Notes for Build 17661 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17661#known-issues-in-this-build)
* Content Source: [windows-iotcore/release-notes/Insider/17661.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/Insider/17661.md)
* Service: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by endyb66** [comment]
Please add 1080p HDMI video output on the Dragonboard by default, since it can't be changed on the Windows Device Portal.
