### ISSUE TITLE
Onboard WIFI and Bluetooth do not work on RPI3B+.

### ISSUE THREAD

**Issue by Parsakarami** [MicrosoftDocs/windows-iotcore-docs#370]
Everyone use this feature in their products, why it`s not support ?

**Comment by saraclay** [comment]
We are working to get RPi3B+ on Windows 10 IoT Core. Stay tuned.

**Comment by kamalcode** [comment]
Installed preview version on Rasberry pi 3b+.
But couldn't detect onboard wifi n bluetooth hardware.
Feeling helpless.
