### ISSUE TITLE
Update to reflect Win 10 spring creators update

### ISSUE THREAD

**Issue by alexmarshall132** [MicrosoftDocs/windows-iotcore-docs#371]
Please update this documentation to reflect the Win 10 spring creators update to the portal. There's no prompt to enter the app certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a5db35-a80e-6db9-9648-cfcaabbe19ca
* Version Independent ID: 52a25746-f8eb-fcf3-cc5a-df5533e08451
* Content: [Install your app on an IoT Core device - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/appinstaller#feedback)
* Content Source: [windows-iotcore/develop-your-app/AppInstaller.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/AppInstaller.md)
* Service: **unspecified**
* Product: **windows-iot**
* GitHub Login: @parameshbabu
* Microsoft Alias: **pabab**

**Comment by saraclay** [comment]
Hi @alexmarshall132 - thank you for the suggestion. We've made the change and it will go live soon: https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/AppInstaller.md
