### ISSUE TITLE
Not able to Enable Remote Desktop on DragonBoard 410c

### ISSUE THREAD

**Issue by omarbarlas** [MicrosoftDocs/windows-iotcore-docs#372]
I installed the Windows 10 IOT (v17134) on DragonBoard 410c and connected to WiFi and next i logged in to Windows Device Portal, and Tried to enable Remote Desktop, but it fails, The Checkbox goes ON but it says: Failed to enable Windows IOT Remote Server. 
Not sure if i am missing a step or something is not right?

**Comment by cyberh0me** [comment]
cant replicate  that issue on 17134 and later

**Comment by omarbarlas** [comment]
Yes it fails to enable it every time, here is the screen shot, the Windows 10 IOT version number i have is v.10.0.17134.1
![image](https://user-images.githubusercontent.com/5050626/40581358-07e45c64-611c-11e8-9b11-b0fa272b89f2.png)

It always show message: Failed to enable Windows IoT Remote Server

![image](https://user-images.githubusercontent.com/5050626/40581406-0add11e4-611d-11e8-8e82-b97572a2d89d.png)

**Comment by cyberh0me** [comment]
can you check if you can control it from command line ?\
ssh into your DragonBoard and
- To query if it is running:
`schtasks.exe /query /tn \Microsoft\Windows\NanoRDP\Start /fo csv /nh`
- To schedule it for startup:
`schtasks.exe /Create /SC ONSTART /TN \Microsoft\Windows\NanoRDP\Start /TR %SystemRoot%\\System32\\NanoRDPServer.exe /RU DefaultAccount /F`
- To Run it:
`schtasks.exe /Run /TN \Microsoft\Windows\NanoRDP\Start`

if this works for you ?

**Comment by omarbarlas** [comment]
Ok these commands worked and Remote Desktop Enabled, thanks, Next i am trying to install latest Insider Build Image to make sure the Serial Port issue is resolved

**Comment by omarbarlas** [comment]
schtasks.exe /Create /SC ONSTART /TN \Microsoft\Windows\NanoRDP\Start /TR %SystemRoot%\\System32\\NanoRDPServer.exe /RU DefaultAccount /F 
Worked on older release of Windows 10 IOT by running that command directly on the Application Command App in side Windows 10 iot, but what i am trying to Run same on later Insider Build it says Access Denied , Windows 10 IOT Version is:  10.0.17692.1000
![image](https://user-images.githubusercontent.com/5050626/43051965-50ac3cd6-8de6-11e8-80aa-0e1e918e4ddc.png)
