### ISSUE TITLE
Visual Studio 15.8 Preview 1.1 hangs on provisioning Raspberry PI 3 running IoT Core build 10.0.17134.48

### ISSUE THREAD

**Issue by wind-rider** [MicrosoftDocs/windows-iotcore-docs#376]
I can connect properly using `kd`

```
PS C:\Program Files (x86)\Windows Kits\10\Debuggers\x86> .\kd -k com:port=5,baud=921600

Microsoft (R) Windows Debugger Version 10.0.17134.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Opened \\.\com5
Kernel Debug Target Status: [no_debuggee]; Retries: [0] times in last [7] seconds.
Waiting to reconnect...
Connected to Windows 10 17134 ARM (NT) Thumb-2 target at (Mon May 21 22:27:55.792 2018 (UTC + 2:00)), ptr64 FALSE
Kernel Debugger connection established.
Symbol search path is: srv*
Executable search path is:
Windows 10 Kernel Version 17134 MP (4 procs) Free ARM (NT) Thumb-2
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 17134.48.armfre.rs4_release_svc_prod1.180427-1806
Machine Name:
Kernel base = 0x80e85000 PsLoadedModuleList = 0x81095d18
Debug session time: Mon May 21 21:45:13.740 2018 (UTC + 2:00)
System Uptime: 0 days 0:17:00.671
```

However, Visual Studio hangs when I try to [provision the Raspberry PI for driver debugging](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/driverdeployment#step-2--provision-device-with-visual-studio).

First I select the Raspberry PI as a mobile device:
![image](https://user-images.githubusercontent.com/3463496/40328609-3c165a06-5d47-11e8-88c0-b6be15cf3b25.png)

After giving the settings:
![image](https://user-images.githubusercontent.com/3463496/40328901-30711bcc-5d48-11e8-885c-bd5d46be3a62.png)

it hangs:
![image](https://user-images.githubusercontent.com/3463496/40328417-9980b6f6-5d46-11e8-84ac-4c332da75cd8.png)

I am using Visual Studio 15.8 Preview 1.1.
My target device is a Raspberry PI 3 running Windows IoT Core build 10.0.17134.48.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5302a6a5-9017-4475-25ee-167a9b816d31
* Version Independent ID: f0bff1be-a4fe-3de0-1ea9-7ec77def3b0c
* Content: [Driver Deployment - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/driverdeployment#step-1--setup)
* Content Source: [windows-iotcore/learn-about-hardware/DriverDeployment.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/DriverDeployment.md)
* Service: **unspecified**
* Product: **windows-iot**
* GitHub Login: @parameshbabu
* Microsoft Alias: **pabab**

**Comment by saraclay** [comment]
Hi @wind-rider - we are looking into this.

**Comment by bfjelds** [comment]
Are KD and VS trying to attach at the same time?  

Not sure if this is what you are seeing, but RPi has had an issue with KD being enabled and VS trying to attach in the past.  

We used to build this into our development boards to combat that problem: `reg add "HKLM\software\Microsoft\VisualStudio\Debugger" /v EmulateExclusiveBreakpoints /t REG_DWORD /d 0 /f`

**Comment by wind-rider** [comment]
I believe that I shut down KD before trying to set up the Visual Studio driver debugger connection.

I tried it multiple times and every time Visual Studio hangs on copying the files for the kernel debugging.

________________________________

**Comment by saraclay** [comment]
@wind-rider Could you file this as a bug following the instructions to Feedback Hub? Thank you!
https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT
