### ISSUE TITLE
DragonBoard 410c SPI NOT sending Data on pins

### ISSUE THREAD

**Issue by omarbarlas** [MicrosoftDocs/windows-iotcore-docs#399]
I am trying to drive 8 pixels DotStar LED strip via SPI0 port of DragonBoard 410, on code side things look fine and sending commands to pins. 

  List<byte> spiDataBytes = new List<byte>();
            spiDataBytes.AddRange(this.startFrame);

            foreach (var pixel in pixels)
            {
                // Global brightness.  Not implemented currently.  0xE0 (binary 11100000) specifies the beginning of the pixel's
                // color data.  0x1F (binary 00011111) specifies the global brightness.  If you want to actually use this functionality
                // comment out this line and uncomment the next one.  Then the pixel's RGB value will get scaled based on the alpha
                // channel value from the Color.
                spiDataBytes.Add(0xE0 | 0x1F); 
             //   spiDataBytes.Add((byte)(0xE0 | (byte)(pixel.A >> 3)));

                // APA102/DotStar leds take the color data in Blue, Green, Red order.  Weirdly, according to the spec these are supposed
                // to take a 0-255 value for R/G/B.  However, on the ones I have they only seem to take 0-126.  Specifying 127-255 doesn't
                // break anything, but seems to show the same exact value 0-126 would have (i.e. 127 is 0 brightness, 255 is full brightness).
                // Discarding the lowest bit from each to make the value fit in 0-126.
                spiDataBytes.Add((byte)(pixel.B >> 1));
                spiDataBytes.Add((byte)(pixel.G >> 1));
                spiDataBytes.Add((byte)(pixel.R >> 1));
            }

            spiDataBytes.AddRange(this.endFrame);

            this.spiDevice.Write(spiDataBytes.ToArray());

But DotStar LEDs would not go ON (Connected to Pin8: SPI0_CLK and Pin14: SPI0_MOSI,) I debugged each individual line of code and it executes fine without error, when i deploy same UWP App on Raspberri Pi3 with its SPI0 Pins it works fine.

Not sure if there is special setup i need to do for DragonBoard 410(Like PullUp or Pull Down Resistor)?

**Comment by cyberh0me** [comment]
https://social.msdn.microsoft.com/Forums/en-US/a9addb37-e556-45f9-8bc7-28dc7441fa2c/audio-out-and-spi0-are-not-working-on-dragonboard-410c-with-windows-10-iot-v17672?forum=WindowsIoT
