### ISSUE TITLE
Can't find info on SD cards compatible with Pi 3

### ISSUE THREAD

**Issue by dirtybirdnj** [MicrosoftDocs/windows-iotcore-docs#401]
I got windows 10 installed on a microSD card, but for some reason wifi doesn't work. I've read that there are "approved" cards that can be used... but can't find any on the site.

**Comment by saraclay** [comment]
Have you tried the SanDisk 64GB microSD card?

**Comment by cyberh0me** [comment]
i dont understand the relation between compatible SD card and WiFi doesn't work, please elaborate
[Hardware compatibility list](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist#storage-media) lists supported SD Cards

**Comment by saraclay** [comment]
Apologies - I misread the question from @dirtybirdnj. I'm assuming you're using a Raspberry Pi? What kind of RPi are you using?
