### ISSUE TITLE
Serial UART Pi3

### ISSUE THREAD

**Issue by PRIMETSS** [MicrosoftDocs/windows-iotcore-docs#417]
Serial Port Usage and Access on RPi2
Raspberry Pi 2 supports the serial transport for communication through the PL011 UART. This is set by default in kernel debugging scenarios. An application or device driver can use the PL011 UART to send and receive data with the PL011 device driver turning off the debugger using the following command:

Is this true for the Pi3 also?
As I'm getting intermittent results trying to use the internal UART to communicate to Serial Devices connected

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65560a2-dbc8-891d-0d19-5d8d2909d8b4
* Version Independent ID: 577d8ef8-6774-02c6-0e70-e9ffdf165c0c
* Content: [Release Notes for Build 17672 - Windows IoT](https://docs.microsoft.com/en-gb/windows/iot-core/release-notes/insider/17672)
* Content Source: [windows-iotcore/release-notes/Insider/17672.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/Insider/17672.md)
* Product: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by saraclay** [comment]
Might be a dup question - closing for now.
