### ISSUE TITLE
How to include MTP in my Custom FFU?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-iotcore-docs#451]
The document [here](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/mtp#how-to-include-mtp-in-your-custom-ffu) lists "How to include MTP in Your Custom FFU". Is there a way to apply the device's USBFN configuration when I customing the FFU? Because the steps of the "[Enabling the MTP USB interface](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/mtp#enabling-the-mtp-usb-interface)" will be done on each devices after install the FFU.
How to add the MTP's Microsoft OS compatible descriptor to the "MSOSCompatIdDescriptor", as there is another interface "DIAG" already exist?

`C:\Data\Users\Administrator>reg query hklm\system\controlset001\control\usbfn\configurations\default

HKEY_LOCAL_MACHINE\system\controlset001\control\usbfn\configurations\default
    bmAttributes    REG_DWORD    0x80
    bMaxPower    REG_DWORD    0xfa
    InterfaceList    REG_MULTI_SZ    DIAG
    MSOSCompatIdDescriptor    REG_BINARY    40000000000104000200000000000000000157494E5553420000000000000000000000000000000001014D545000000000000000000000000000000000000000
`

![qq 20180620181815](https://user-images.githubusercontent.com/13234209/41652801-be7864f4-74b6-11e8-9d0b-e1c543201387.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0957bd-ef26-e0aa-24ad-ca3aa6c565e4
* Version Independent ID: 222b67af-21c5-2f13-43e6-b03c9fae703c
* Content: [Media Transfer Protocol - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/mtp)
* Content Source: [windows-iotcore/connect-your-device/MTP.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/connect-your-device/MTP.md)
* Product: **windows-iot**
* GitHub Login: @PawelWMS
* Microsoft Alias: **pawelwi**

**Comment by PawelWMS** [comment]
Hi there,<br/>
<br/>
I am one of the engineers working for Microsoft and I will try to answer your questions.<br/>
<br/>
If I understood you correctly, you would like to create your custom FFU with MTP already fully configured, so that you do not have to make manual changes to USBFN configuration after flashing. This can be broken down into two steps:<br/>
<br/>

1. **Creating your own USBFN configuration.**<br/>
<br/>
    The documentation you are referring to describes a generic scenario of adding MTP to an already existing configuration, since many other USB interfaces may be added independently of MTP. If you are starting with the default configuration and would like to enable MTP, then I would suggest creating your own configuration. You can do this by:<br/>
<br/>
a. adding a ```CurrentConfiguration``` value under ```HKEY_LOCAL_MACHINE\CurrentControlSet\Control\USBFN``` with an arbitrary ```REG_SZ``` value;<br/>
b. adding a subkey ```HKEY_LOCAL_MACHINE\CurrentControlSet\Control\USBFN\[CurrentConfiguration]```, where ```[CurrentConfiguration]``` is equal to the value you’ve added in the first step;<br/>
c. following steps 2. and 3. from ***Enabling the MTP USB interface*** on the documentation page.<br/>
<br/>
Detailed documentation describing USBFN’s registry keys and values is available [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-registry-settings-for-a-function-controller-driver). <br/>
<br/>
2. **Applying the USBFN configuration to the FFU**.<br/>
    <br/>
    The USBFN configuration is nothing more than a change in the registry. If you need it permanently added to the FFU, then please follow these [instructions](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/add-a-registry-setting-to-an-image).<br/>
<br/><br/>
Here is some additional information, in case you would like to learn more about the "MSOSCompatIdDescriptor" value and how to create a configuration with multiple interfaces or an interface different than MTP:<br/>
<br/>
    The value under "MSOSCompatIdDescriptor" is a byte representation (little-endian!) of the extended compat ID descriptor. The descriptor's structure and how it can be modified is described in<br/>
    the documentation available at the bottom of [this page](https://msdn.microsoft.com/en-us/windows/hardware/gg463179.aspx).<br/>
    The "OS_Desc_CompatID.doc" file has the most relevant information along with an example of a descriptor containing the MTP interface.<br/>
    The page also lists the compatible and sub-compatible IDs for MTP, which are a needed to build a correct descriptor for this interface.<br/>
<br/>
I hope that these tips will be helpful. Please let us know, in case something is still unclear and thank you for reaching out!<br/>
<br/>
All the best,<br/>
Pawel Winogrodzki, Microsoft<br/>

**Comment by moyanming** [comment]
Hi @PawelWMS , 
Thank you for your detailed answers!
1. I use the Dragonboard 410c with BSP V2112, iot OS V10.0.17134.1, ADK v17134.
2. There is no subkey "HKEY_LOCAL_MACHINE\CurrentControlSet". BTW, is it OK if I create this subkey: CurrentControlSet within the [Lab 1c](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/add-a-registry-setting-to-an-image)?
![qq 20180621121458](https://user-images.githubusercontent.com/13234209/41720862-e927f878-7596-11e8-851f-1d5b16257987.jpg)

3. I program the FFU with IOT_MTP feature and found that there is a new MTP interface in the: hklm\system\controlset001\control\usbfn\interfaces\.
![qq 20180621183838](https://user-images.githubusercontent.com/13234209/41721155-c18773c4-7597-11e8-9161-7719aac68c74.jpg)

I don't know the "DIAG" is and I never use this maybe, so I delete the "DIAP" interface and it's MSOSCompatIdDescriptor. I add a new MTP interface successfully but there is a error when I add the MSOSCompatIdDescriptor of the MTP:
![qq 20180621182621](https://user-images.githubusercontent.com/13234209/41721173-c9eb0418-7597-11e8-9239-350fdab6b1fb.jpg)
So, I skip the MSOSCompatIdDescriptor and test with my pc. It seems that the PC can enumerate the emmc and SD card successfully.
![qq 20180621211413](https://user-images.githubusercontent.com/13234209/41721311-229cd15e-7598-11e8-8e89-5c54cdf68bb4.jpg)
BTW, how to fix the MSOSCompatIdDescriptor of the MTP? How to delete the registry, as the registry is the same name?
Best regards.

**Comment by moyanming** [comment]
Hi @PawelWMS,
Yes, I want to do all the MTP configurations when I custom my FFU.
It seems my steps are easy way to add the MTP. But I still have question:
How to change the already exist registry subkeys InterfaceList and MSOSCompatIdDescriptor of the DIAG to the MTP when I do the Lab 1c?
Best regards.

**Comment by PawelWMS** [comment]
Hi @moyanming,<br/>
<br/>
Ad. 2. I will discuss this with the owner of that documentation page - it might be a typo. Thank you for noticing. You are using the correct path right now, with the *System* key.<br/>
Ad. 3. The new interface is expected to be there - it has been added, so users could just create/modify their configuration by adding that new interface. Every interface inside `InterfaceList` needs to be defined first under the *Interfaces* subkey.<br/>
<br/>
I have dug a bit deeper and it is ok to skip *MSOSCompatIdDescriptor* in case of well-known interfaces like MTP. It can, however, make it somewhat easier to potentially add another, non-standard interface into the configuration in the future. Plus, it makes the settings more consistent across configurations. Adding it in this case is entirely up to you.<br/>
<br/>
I have not seen any issues with your *reg* command, so maybe a special character got copied from the documentation page and is not visible in the command line. Please, try double-checking that.<br/>
<br/>
I am guessing you have hit a conflict error with your changes. The current recommendation is to not modify pre-existing registry values from the base image, as they get refreshed or might get overwritten by a system update. That is why I suggested creating a new configuration. If you are worried about the *DIAG* interface, then you can add the `IncludeDefaultCfg` value under `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\USBFN` and set it to 1. This will make sure USB loads both the default and your configuration. You just have to make sure the interfaces do not repeat. There are only the *DIAG* and *MTP* interfaces in your scenario, so you should be fine.

**Comment by moyanming** [comment]
Hi @PawelWMS ,
Thank you for your answers!
I following the steps [here](https://github.com/PawelWMS/windows-iotcore-docs/blob/Fixing_MTP_Doc/windows-iotcore/connect-your-device/MTP.md) (which is a "Pull requestes": Claryfing MTP configuration. #458) and all the configurations can be done within the FFU.

Best regards.

![qq 20180622210206](https://user-images.githubusercontent.com/13234209/41778082-1a141146-7660-11e8-9dbd-14b2c14a239d.jpg)

**Comment by PawelWMS** [comment]
You are welcome. Please let me know, if you still encounter any issues.

All the best,
Pawel Winogrodzki, Microsoft
