### ISSUE TITLE
Uninstall driver on iot

### ISSUE THREAD

**Issue by kickyourass** [MicrosoftDocs/windows-iotcore-docs#456]
I finished the step "applyupdate -stage xxxx.cab" and "applyupdate -commit".
After reboot my driver works well, however I want to update my driver, the same steps shows the driver already existed and forbid me to do that.
And I cannot find the way to uninstall the driver. Could anyone help me?
I've try 'devcon remove', but it seems just temporary disable.

**Comment by cyberh0me** [comment]
https://social.msdn.microsoft.com/Forums/en-US/e63057b6-82d6-40b9-8976-dfc4565fbb63/uninstall-the-driver-on-iot-raspberry-pi3?forum=WindowsIoT

**Comment by saraclay** [comment]
@kickyourass Did this help?

**Comment by kickyourass** [comment]
That's my reply in MSDN forum. replacing .sys way works well.
