### ISSUE TITLE
Typo in release notes

### ISSUE THREAD

**Issue by PRIMETSS** [MicrosoftDocs/windows-iotcore-docs#474]
In most release notes 

I think 

bcedit /set debug off 

should be

bcdedit /set debug off 

Will edit docs and submit pull request
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d726d72c-cc76-9dea-8710-ff9fdd04e0e0
* Version Independent ID: 0b064bcb-73e0-2ecf-dfb9-48a3e1b7682b
* Content: [Release Notes for Build 17692 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17692)
* Content Source: [windows-iotcore/release-notes/Insider/17692.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/Insider/17692.md)
* Product: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by saraclay** [comment]
Thanks! Just made the change.
