### ISSUE TITLE
DragonBoard 410 Windows 10 IOT v17692 , SPI and Serial UART don't work

### ISSUE THREAD

**Issue by omarbarlas** [MicrosoftDocs/windows-iotcore-docs#482]
I have tried Windows 10 IOT v17692 on DragonBaord 410 and the Serial UART and SPI ports are not working, same code works fine on Raspberri Pi 3, but world not send any data to Serial or SPI Pins of DragonBoard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560c6386-43f3-d102-d4d8-31a1a37f4c04
* Version Independent ID: 0f8e49e6-9f9f-301c-d261-0546e9d15ec9
* Content: [Release Notes for Build 17692 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/currentinsider)
* Content Source: [windows-iotcore/release-notes/CurrentInsider.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/CurrentInsider.md)
* Product: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by cyberh0me** [comment]
https://social.msdn.microsoft.com/Forums/en-US/0f936077-00ea-4025-b95c-29b60058a8af/17661-dragonboard-410c-no-uart?forum=WindowsIoT

https://social.msdn.microsoft.com/Forums/en-US/2bc5a523-fb35-414a-8801-ec547b203c5c/new-flight-17692-released-for-insiders?forum=WindowsIoT
