### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by chunkbin** [MicrosoftDocs/windows-iotcore-docs#483]
"To facilitate easy enablement of key secrutiy features" should read "To facilitate easy enablement of key security features"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50c4a91f-8e90-2d9f-951b-b16fab02d241
* Version Independent ID: e3130512-d742-d239-25ca-9ab134ff79a9
* Content: [Enabling Secure Boot, BitLocker, and Device Guard on Windows 10 IoT Core - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/securebootandbitlocker)
* Content Source: [windows-iotcore/secure-your-device/SecureBootAndBitLocker.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/secure-your-device/SecureBootAndBitLocker.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Thanks! I've submitted a PR for this.
