### ISSUE TITLE
Running headless apps on IoT Enterprise

### ISSUE THREAD

**Issue by greyghostbrewery** [MicrosoftDocs/windows-iotcore-docs#484]
How do you invoke / configure a headless app to run at boot on IoT Enterprise?  The document at the link below indicates that IoT Enterprise does support headless apps, however the iotstartup CLI tool does not appear to be available.

http://wincom.blob.core.windows.net/documents/Windows_10_IoT_Platform_Overview.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfeba98b-ce89-613d-f31e-400faf6eb8c2
* Version Independent ID: 6aa7fea5-8c12-3306-4a20-f9ed8dc21344
* Content: [Background Applications - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/backgroundapplications)
* Content Source: [windows-iotcore/develop-your-app/BackgroundApplications.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/BackgroundApplications.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi there,

At the moment, a fix is coming in the fall with the RS5 update.
