### ISSUE TITLE
Which image should I download if my board is intel joule 570x

### ISSUE THREAD

**Issue by jimmyfans913** [MicrosoftDocs/windows-iotcore-docs#488]
Hi, I want to install win 10 IoT installed on joule 570x. Seen a supported list of Raspberry and others, and I wonder which  version of image should I use?

**Comment by cyberh0me** [comment]
with the Fall Creators update (Build Number 16299. October 2017) support for Intel Joule platform was dropped
more information in Release notes https://docs.microsoft.com/en-us/windows/iot-core/release-notes/commercial/fallcreatorsupdate
