### ISSUE TITLE
Windows 10 IoT Enterprise support?!

### ISSUE THREAD

**Issue by MoiMoiDG** [MicrosoftDocs/windows-iotcore-docs#489]
Hi,

this documentation refers to services for Windows 10 IoT Core explicitly. Are they valid for Windows 10 IoT Enterprise as well? To which extent?

Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27e43d1-43a6-1cc3-8a60-8c3efa256553
* Version Independent ID: 631a1234-d235-37bf-aac2-c0c25527a76b
* Content: [Windows 10 IoT Core Services - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/commercialize-your-device/iotcoreservicesoverview)
* Content Source: [windows-iotcore/commercialize-your-device/IoTCoreServicesOverview.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/commercialize-your-device/IoTCoreServicesOverview.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Windows 10 IoT Enterprise is a different product - please see this article for more information: https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-enterprise
