### ISSUE TITLE
Cannot run UWP app as Server for localhost service calling!

### ISSUE THREAD

**Issue by Parsakarami** [MicrosoftDocs/windows-iotcore-docs#518]
when i call CheckNetIsolation.exe LoopbackExempt -is -n=&lt;MyApp&gt; command i get following error :

Could not add exemption: 0x80320009
Error occurred -2144206839 - 80320009

can use a UWP app as server for response request with SocketListener ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f952bdf-550a-c165-35f2-9be9998b9eef
* Version Independent ID: 699068d8-cc46-28f2-a4b1-19138400d443
* Content: [Communicating with Localhost - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/loopback)
* Content Source: [windows-iotcore/develop-your-app/Loopback.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/Loopback.md)
* Product: **windows-iot**
* GitHub Login: @paulmon
* Microsoft Alias: **paul.monson**

**Comment by paulmon** [comment]
It looks like this is the error you get when you CheckNetIsolation.exe LoopbackExempt -is -n=<MyApp> more than once with the same <MyApp>

**Comment by saraclay** [comment]
Closing for now. Please reopen if anything comes up.
