### ISSUE TITLE
Mobile broadband can't connect when roaming

### ISSUE THREAD

**Issue by crates-barrels** [MicrosoftDocs/windows-iotcore-docs#548]
Hi,

I'm having an issue on Windows IoT Core when trying to connect an MBN device to the cellular network when roaming.
The device is a Vodafone (Huawei) K5150 and is working normally when not roaming.
I added a profile using the following netsh command:
`netsh mbn add profile interface="Cellular" name="c:\profile.xml"`
The device will then automatically establish a connection to the network.

However, if the device is roaming, it will not connect automatically and if I try to establish the connection manually, an error is shown immediately:
`netsh mbn connect interface="Cellular" connmode=name name="cellularprofile"`
Result: `Connect Failure: error 0x139f.`
I couldn't find more information about this error code on the internet.
This is tested with 3 different (roaming enabled) SIM cards from different providers, but they all have the same problem.

I also tested this on a Windows 10 laptop (non IoT Core) using the same Vodafone device, same SIM card and exactly the same profile. The result here is as expected when connecting manually using the same netsh command: the device connects to the cellular network and no errors are shown.
The Windows versions are the same for both devices: 10.0.17134.

So my questions are:
- What does error 0x139f mean?
- How can I solve this? Is this a restriction that can be controlled by changing a registry key? Am I missing an IoT Core feature in my image perhaps? Is there a setting unsupported in the WWAN profile on IoT Core? Or maybe a bug in Windows IoT Core?

Any help would be greatly appreciated!

**Comment by saraclay** [comment]
@crates-barrels we are looking into this.

**Comment by crates-barrels** [comment]
Thanks! Let me know if you need any more information.

**Comment by SlavyMihov** [comment]
Hi @crates-barrels,

There are two things to consider when enabling roaming:
1.	The _profile.xml_ configures roaming and sets the behavior to automatically establish a connection to the cellular network.

    To set a profile for roaming please refer to https://docs.microsoft.com/en-us/windows/desktop/mbn/schema-root
```
  <!-- applicability to any combination of home carrier, partner MOs and non-partner MOs, except for HomeAndNonPartner -->
  <xs:simpleType name="roamApplicabilityType">
    <xs:restriction base="xs:token">
       <xs:enumeration value="NonPartnerOnly"/>
       <xs:enumeration value="PartnerOnly"/>
       <xs:enumeration value="HomeOnly"/>
       <xs:enumeration value="HomeAndPartner"/>
       <xs:enumeration value="PartnerAndNonpartner"/>
       <xs:enumeration value="AllRoaming"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="roamControlType">
    <xs:restriction base="xs:token">
       <xs:enumeration value="AllRoamAllowed"/>
       <xs:enumeration value="PartnerRoamAllowed"/>
       <xs:enumeration value="NoRoamAllowed"/>
    </xs:restriction>
  </xs:simpleType>
```
To set a profile for automatic connection, select “auto”.
```
  <!-- Connection Mode, default is "manual" -->
    <xs:element name="ConnectionMode" minOccurs="0">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <!-- manual connect always -->
          <xs:enumeration value="manual" />
          <!-- auto connect always -->
          <xs:enumeration value="auto" />
          <!-- auto connect when not roaming -->
          <xs:enumeration value="auto-home"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
```
2.	Another factor is that the per-interface roaming policy must be satisfied. By default that policy is set to FALSE (“Home carrier only”).
This can be queried and changed in command line via `netsh mbn get/set dataroamcontrol`.

    Example:
```
    netsh mbn show dataroamcontrol int=*
    netsh mbn set dataroamcontrol interface=Cellular profileset=all state=all
    netsh mbn set dataroamcontrol help
```
You may get error **0x139f** (_ERROR_INVALID_STATE_) in the case when the device is roaming but the roaming policy disallows data roaming - error on a connect request sent to _wwansvc_.

**Comment by crates-barrels** [comment]
Thank you @SlavyMihov! Number 2 did the trick.

Initially the interface roaming policy was indeed set to "Home carrier only", after your second netsh command the policy will be "Home, partner and roaming carriers" and the device connects automatically to the roaming network as I expected.

**Comment by e-leoni** [comment]
Hi @crates-barrels , I have the same problem, but if I launch the command:
`netsh mbn show dataroamcontrol int=*`
I receive this response:
> All Host Profiles          : Home, partner and roaming carriers
Can you confirm that dongle 3G works fine with raspberry and iot core?
