### ISSUE TITLE
Dragonboard 410c Boot Logo Orientation

### ISSUE THREAD

**Issue by endyb66** [MicrosoftDocs/windows-iotcore-docs#569]
When setting the display orientation to portrait mode, the boot logo (Qualcomm Snapdragon logo) does not change it's orentation, like the Windows boot logo on the RPi3 does. It would be very nice, if this logo does also change to the correct orientation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3cc8f9f-ed48-fa2d-77b6-0fa8503ae30d
* Version Independent ID: e590ba03-e203-ece7-d2f5-03f22766a1f6
* Content: [April 2018 Update - Build 17134 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/commercial/april2018update)
* Content Source: [windows-iotcore/release-notes/commercial/April2018Update.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/commercial/April2018Update.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @endyb66, this sounds like a bug. Do you mind filing a bug for this? https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT
