### ISSUE TITLE
Asus Thinker Board

### ISSUE THREAD

**Issue by fatihgol** [MicrosoftDocs/windows-iotcore-docs#593]
Hello ,
I want to use Windows IOT on the Asus Thinker Board, but there is no version. Is there a development in this regard? or is there a transaction to enable me to use it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257dc32b-f302-db2a-2571-8f217007d893
* Version Independent ID: 92b2f238-f621-3feb-5b5b-07aed095b115
* Content: [Suggested Prototype Boards - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/tutorials/quickstarter/prototypeboards#windows-10-iot-core-development-devices)
* Content Source: [windows-iotcore/tutorials/quickstarter/PrototypeBoards.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/quickstarter/PrototypeBoards.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @fatihgol, the ASUS Tinkerboard uses a Rockchip SoC which is not officially supported by us. There are cases in which Rockchip and other 3rd parties did work with some of their SoCs to get them working on IoT Core, however.
