### ISSUE TITLE
Request 64-bit ARM drivers for WinIoT for RPi

### ISSUE THREAD

**Issue by DRSDavidSoft** [MicrosoftDocs/windows-iotcore-docs#606]
@saraclay 

I understand that IoT core on Raspberry Pi implements 32-bit ARM drivers for use in the official images provided by Microsoft, however these drivers are not compatible with 64-bit binaries.

I'd like to ask if there is any chances of compiling 64-bit drivers by Microsoft. Is it possible?

These drivers could be used on [WoR project](https://www.worproject.ml/faq) to boot 64-bit UEFI Windows on a Raspberry Pi which are currently lacking at the moment (https://github.com/andreiw/RaspberryPiPkg/issues/12#issuecomment-383382430).

Currently, we would appreciate the Ethernet or Wifi drivers for **SMSC9512** controller on **BCM2837** SoC (ARMv8 64-bit)!

**Comment by saraclay** [comment]
Hi @DRSDavidSoft, at the moment, we are not compiling 64-bit drivers - though that may be possible for other hardware in the future. Regarding the drivers you're requesting, it's in their hands to support 64-bit. I wish I had better news for you. Good luck in your endeavors.
