### ISSUE TITLE
When will we see support for more boards?

### ISSUE THREAD

**Issue by sevsev9** [MicrosoftDocs/windows-iotcore-docs#609]
I love windows 10 IOT. That is why I am waiting for Microsoft to quickly add more powerful boards such as the new RockPro64, which feautures 4 Gigs of ram and an PCIe x4 slot compatible with nvme. Also a Hexacore package is included which would be awesome to use with Windows 10 IOT!!

Any chances of seeing further support soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257dc32b-f302-db2a-2571-8f217007d893
* Version Independent ID: 92b2f238-f621-3feb-5b5b-07aed095b115
* Content: [Suggested Prototype Boards - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/tutorials/quickstarter/prototypeboards)
* Content Source: [windows-iotcore/tutorials/quickstarter/PrototypeBoards.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/quickstarter/PrototypeBoards.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @sevsev9 - that is great to hear, thank you so much. At the moment, we are sticking to what you see in our documentation. We encourage customers to contact the board manufacturers to see if there would be interest in partnering with Windows 10 IoT.
