### ISSUE TITLE
Example of integration with Azure Speech API

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/windows-iotcore-docs#622]
Would be useful to have an example of IoT Core app with integration to Azure's Speech API for STT and TTS  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f903d358-1345-34e3-96e2-abb9982982ae
* Version Independent ID: 1728caf0-4ad0-c5b1-a78c-bb4d44827005
* Content: [Speech resources and samples - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/extend-your-app/speech)
* Content Source: [windows-iotcore/extend-your-app/Speech.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/extend-your-app/Speech.md)
* Product: **windows-iot**
* GitHub Login: @zhuridartem
* Microsoft Alias: **artemz**

**Comment by saraclay** [comment]
Thank you for the suggestion, @jjgriff93. We'll be working on more Azure Speech scenarios hopefully in the future. Since I see you are also a fellow Microsoft employee, if you come up with anything with this scenario, we'd be more than happy to attribute a contribution from you.
