### ISSUE TITLE
Wiring Example Links Not workin

### ISSUE THREAD

**Issue by matangpanchal** [MicrosoftDocs/windows-iotcore-docs#624]
Example links given on the page is not working seems outdated, and the page they loads don't have any wiring samples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b5c34ab-52d1-f028-a5a0-1bb7f9c42567
* Version Independent ID: a922056b-ecab-e0c5-709b-3d01fe9ac368
* Content: [Arduino Wiring Project Guide - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/arduinowiringprojectguide)
* Content Source: [windows-iotcore/learn-about-hardware/ArduinoWiringProjectGuide.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/ArduinoWiringProjectGuide.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Thank you for the heads-up, @matangpanchal. We will investigate this. Closing out for now.
