### ISSUE TITLE
Link to default app source

### ISSUE THREAD

**Issue by mwettste** [MicrosoftDocs/windows-iotcore-docs#639]
The link to the default iot core app leads to a repository where still the old default application is hosted. Has the source code of the new version not been published yet, or is the code hosted in a new repository and the link should be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6854849-9812-2667-11cc-5506c8e36e22
* Version Independent ID: 94814756-3eb3-b488-778f-7ad34fd96ee6
* Content: [Windows 10 IoT Core Default App - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/iotcoredefaultapp)
* Content Source: [windows-iotcore/develop-your-app/IoTCoreDefaultApp.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/IoTCoreDefaultApp.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi there - the code should be published by 10/2! We got ahead of ourselves with the documentation :)

**Comment by mwettste** [comment]
Cool, thanks for the feedback :)

**Comment by mwettste** [comment]
I would be interested in an update as well. The code for the sample app is still for the old version.
