### ISSUE TITLE
Insider Preview Builds

### ISSUE THREAD

**Issue by HaydenHolcomb** [MicrosoftDocs/windows-iotcore-docs#673]
It seems like not all of the Release Notes for the Insider Previews are posted. For instance, 17704, 17728, 17744, 17751, 17754, 17758, and 17763.
Also it think that 17723 should actually be 17733. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b95927-b784-bb3e-d630-5421606c5ef2
* Version Independent ID: 610614df-2534-de7a-f47b-1d7ab47245e9
* Content: [Release Notes for Build 17672 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17686)
* Content Source: [windows-iotcore/release-notes/Insider/17686.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/Insider/17686.md)
* Product: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by saraclay** [comment]
Hi @HaydenHolcomb - there are different kinds of releases. What you might be thinking of are the Insider Fast releases, which can be found on MSDN here: https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT The ones you're seeing here are not always published weekly. When they are, the release notes are published here.
