### ISSUE TITLE
Typo for AD2P-SINK and AD2P-SRC?

### ISSUE THREAD

**Issue by VitorX** [MicrosoftDocs/windows-iotcore-docs#674]
Should AD2P-SINK and AD2P-SRC be A2DP-SINK and A2DP-SRC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60f784b7-a698-cb6e-6789-6b9719970470
* Version Independent ID: df8f2bb4-9b0d-4db2-7c18-b9900ded9f19
* Content: [October 2018 Update - Build 17763 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/commercial/october2018update)
* Content Source: [windows-iotcore/release-notes/commercial/October2018Update.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/commercial/October2018Update.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @VitorX, you are correct. These notes were copied from another document that originally had the typo. Thank you for pointing this out.
