### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by tomitanska** [MicrosoftDocs/windows-iotcore-docs#696]
It's going to bee intresting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e816c04b-7c8c-dc54-6382-7c7f2ba532c0
* Version Independent ID: 0e949478-2401-c768-49c6-b21d01d80aa3
* Content: [Get Started Overview - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/tutorials/tutorials)
* Content Source: [windows-iotcore/tutorials/Tutorials.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/Tutorials.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Issue makes no sense. Closing.
