### ISSUE TITLE
Mic and speaker arrays

### ISSUE THREAD

**Issue by pbharat84** [MicrosoftDocs/windows-iotcore-docs#719]
Can you please list out some of the microphone and speaker arrays that are supported by windows IOT. I have been looking for these for a while and no luck finding them. Appreciate your help.

**Comment by saraclay** [comment]
Hi @pbharat84, unfortunately because there are a lot of peripherals we do support, we are unable to maintain the entire list. We ask that our users contribute their findings to the list of supported hardware.
