### ISSUE TITLE
C# Code snippets should use csharp as their language specifier 

### ISSUE THREAD

**Issue by DuncanmaMSFT** [MicrosoftDocs/windows-iotcore-docs#748]
This will produce the desired syntax highlighting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525c643a-0e4f-a732-cc19-bc304acc5862
* Version Independent ID: 028d320a-4eb6-a419-4933-b64c7abdf145
* Content: [Raspberry Pi 2 & 3 Pin Mappings - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/pinmappings/pinmappingsrpi)
* Content Source: [windows-iotcore/learn-about-hardware/PinMappings/PinMappingsRPI.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/PinMappings/PinMappingsRPI.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @DuncanmaMSFT, thanks for the tip!
