### ISSUE TITLE
Can't set the volume of the Speaker!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-iotcore-docs#749]
Hi all,
DragonBoard 410c, Audio Messanine Board, test on Windows 10 IoT Core v10.0.17763.1 OS.
I have tried 3 different ways to set the volume of the Speaker, but there is no change of the Speaker. This Speaker is work fine and loudly.
1. Invalid:
 iotcoreaudiocontroltool r 58.6
2. Invalid:
Change the volume from the Audio Control of the Windows Device Portal.
3. Invalid:
Change the volume by use the button (- and +) on the Dragonboard 410c.

How to fix this?

BTW, change the capture device volume is successfully, but it seems that the [Microphone is no work at all](https://github.com/MicrosoftDocs/windows-iotcore-docs/issues/727).

Best regards.

![qq 20181019175541](https://user-images.githubusercontent.com/13234209/47213589-10993580-d3ce-11e8-9f91-74a47c9aea84.jpg)
![qq 20181019175341](https://user-images.githubusercontent.com/13234209/47213604-1b53ca80-d3ce-11e8-980c-145c2d8f7db4.jpg)
![qq 20181019175229](https://user-images.githubusercontent.com/13234209/47213755-77b6ea00-d3ce-11e8-8889-ace41c7b669c.jpg)
![qq 20181019175404](https://user-images.githubusercontent.com/13234209/47213617-24dd3280-d3ce-11e8-9d28-687bee2de287.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2599338-019c-10e6-13e6-620630f42b95
* Version Independent ID: caafa3ff-dfe6-5af5-efe2-978c3469c2b2
* Content: [Release Notes for Build 17744 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17744)
* Content Source: [windows-iotcore/release-notes/Insider/17744.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/Insider/17744.md)
* Product: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by endyb66** [comment]
@moyanming, another way would be to change the volume in your code, on the MediaPlayer. But it seems that this is a bug what you described. A few weeks ago, i had connected speakers directly to the J7 header on the Dragonboard, and there i was also not able to change the volume with one of your three options. So it has to be a bug i think.

**Comment by moyanming** [comment]
Hi @endyb66 ,
Yes, the MediaPlayer.Volum can set or get the audio volum for the media playback. This is OK for your own instance of the MediaPlayer but can't suitable for the audio which is play by the web browser.

**Comment by endyb66** [comment]
@moyanming, you're right, in your use case this is not helpful. Hope we are getting news about all these analog / audio issues we have.

**Comment by saraclay** [comment]
Hi - I'm trying to find the right person to help with this. Please stay tuned.

**Comment by saraclay** [comment]
Hi @endyb66 and @moyanming, we're advising people to take a look at this guide from Qualcomm: https://developer.qualcomm.com/download/db410c/stereo-connector-and-audio-routing-application-note.pdf 

I'm closing this out for now. Feel free to reopen if the guide does not answer your questions.

**Comment by endyb66** [comment]
Hi @saraclay, please reopen, this guide does not cover the problematic, which seems to be an issue with Windows 10 IoT Core.

**Comment by saraclay** [comment]
Please file this issue on our MSDN forums here: 
https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT

We explicitly say on our homepage that we handle documentation-related issues, such as typos or suggestions. However, this is falling in line with customer support, which the issues channel does not handle. 

It seems that you are working on a complex project, so it is advised that you work with a distributor. You can find a list of our distributors here: http://wincom.blob.core.windows.net/documents/Windows_IoT_Distributor_Information.pdf
