### ISSUE TITLE
Cannot assign a reviewer to my pull request

### ISSUE THREAD

**Issue by tscholze** [MicrosoftDocs/windows-iotcore-docs#799]
Hi folks,
I cannot assign a reviewer to [my pull request](https://github.com/MicrosoftDocs/windows-iotcore-docs/pull/798) but I have to get the request approved. Maybe somebody could help me to get this fixed.

I also cannot see the `develop` branch of the docs as suggested by the "how to contribute" file:

> When making contributions, please submit your Pull Request (PR) to the Develop branch.

Thanks for helping my out!

![image](https://user-images.githubusercontent.com/5583469/47615375-5c26a000-daae-11e8-80d9-2ffe49135486.png)

**Comment by saraclay** [comment]
Hi @tscholze - apologies for not seeing this earlier. Looks like you figured it out - thank you for your contribution!

**Comment by tscholze** [comment]
@saraclay thanks for merging! It's great to contribute to such a large project. 

I hope I could use this pull request as an entry to maybe win a hacktoberfest shirt :)
