### ISSUE TITLE
Link to Windows 10 IoT Core Dashboard is broken

### ISSUE THREAD

**Issue by logan12358** [MicrosoftDocs/windows-iotcore-docs#800]
The link to the Windows 10 IoT Core Dashboard ("1. Download the Windows 10 IoT Core Dashboard here.") points to &lt;https://developer.microsoft.com/en-us/windows/iot/Downloads&gt;, which isn't found. I think that a working link is &lt;https://docs.microsoft.com/en-us/windows/iot-core/downloads&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6547b7e1-4e53-9510-e550-ac2d369da6d9
* Version Independent ID: a3c18768-7ee4-4e7a-2ca4-f6f6c31f342a
* Content: [Setting up your device - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/tutorials/quickstarter/devicesetup#using-the-iot-dashboard-raspberry-pi-and-minnowboard)
* Content Source: [windows-iotcore/tutorials/quickstarter/DeviceSetup.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/quickstarter/DeviceSetup.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Thank you @logan12358 - we've received multiple issues about this and have fixed this. It seems to be a redirect error.

**Comment by sankalp123321** [comment]
It is not fixed. The link for downloading Windows 10 IoT Dashboard redirects to a broken page:
https://learn.microsoft.com/en-us/windows/iot-core/downloads

If you have a working link, can you please share over here?

<img width="546" alt="image" src="https://user-images.githubusercontent.com/43979892/198903655-798d3874-7e77-4f7c-bbe9-883055b0f9c8.png">
