### ISSUE TITLE
Miracast over Infrastructure?

### ISSUE THREAD

**Issue by mms-** [MicrosoftDocs/windows-iotcore-docs#812]
Does it work with Miracast over Infrastructure? i.e. Ethernet https://docs.microsoft.com/en-us/surface-hub/miracast-over-infrastructure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90b88cb-4f0a-23e4-ec60-c398df87e52b
* Version Independent ID: 935d0581-ed6c-9b98-8a10-58d095170eca
* Content: [Miracast on IoT Core - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/miracast)
* Content Source: [windows-iotcore/connect-your-device/Miracast.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/connect-your-device/Miracast.md)
* Product: **windows-iot**
* GitHub Login: @derekameer
* Microsoft Alias: **demeer**

**Comment by saraclay** [comment]
Hi @mms-, this seems to be more of a desktop Windows/Windows IoT Enterprise feature. I don't think our team has tried this for IoT Core. I think it's worth giving a shot - please let us know if it does work for you.
