### ISSUE TITLE
Does IOT_MTP feature enable WPD device connection?

### ISSUE THREAD

**Issue by mms-** [MicrosoftDocs/windows-iotcore-docs#813]
Looking to connect to a Nikon camera and use Windows WPD API to control the camera, i.e. capture image, not simple mass storage file transfer.

Drivers on Windows 10 used by a device like this are : 
wpdmtpdr.dll
winusb.sys
wpdupfltr.sys
wudfrd.sys
wpdmtp.dll
wpdmtpus.dll

Can these be packaged into a driver and installed on IoT Core? Both ARM and x86?

Thanks.

**Comment by saraclay** [comment]
Hi @mms-, for non-documentation-related questions such as this one, please use our MSDN forums, where we have team members dedicated to monitoring these sorts of questions: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT 

Thanks!
