### ISSUE TITLE
Open build warnig for multiple authors

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/windows-iotcore-docs#835]
In #820 I noticed some warnings about multiple authors on articles. I don't think the platform supports that because it tries to `@` a single author to review the changes. If it does, it would probably be a Markdown list with a multi-line `-` rather than a comma separated list.

**Comment by saraclay** [comment]
Thank you for the note @nschonni! We will make that change. You've been so helpful - we're grateful for your contributions!
