### ISSUE TITLE
About the known issue for Remote Client on Raspberry PI

### ISSUE THREAD

**Issue by VitorX** [MicrosoftDocs/windows-iotcore-docs#867]
This known issue is listed for the **commercial release not**, but it is not mentioned in the **inside previews release note**. This will misleads customers to think the issue was fixed. Is it also possible to add this known issue in the **inside previews release note**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2599338-019c-10e6-13e6-620630f42b95
* Version Independent ID: caafa3ff-dfe6-5af5-efe2-978c3469c2b2
* Content: [Release Notes for Build 17744 - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17744)
* Content Source: [windows-iotcore/release-notes/Insider/17744.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/release-notes/Insider/17744.md)
* Product: **windows-iot**
* GitHub Login: @zeeshanfurqan
* Microsoft Alias: **zeeshan.furqan**

**Comment by saraclay** [comment]
This has been resolved. Thank you for filing! Feel free to submit a PR next time.
