### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces method cause "the method or operation is not implemented." exception

### ISSUE THREAD

**Issue by v-liujxu** [MicrosoftDocs/windows-iotcore-docs#88]
When i call NetworkInterface.GetAllNetworkInterfaces method( running with RPi 3 ), it causes "the method or operation is not implemented." exception.The windows iot core version is 15063.and i have updated System.Net.NetworkInformation to version 4.3.0.

**Comment by derekameer** [comment]
This API works in the Creator's Update. If you update IoT Core to version 16299 via the Dashboard it should work.

**Comment by derekameer** [comment]
Docs fixed with pull request #123 , now merged
