### ISSUE TITLE
More USB Mobile Broadband Modem 

### ISSUE THREAD

**Issue by rtarta** [MicrosoftDocs/windows-iotcore-docs#885]
Need more USB Mobile Broadband Modem driver support, do not think only devices work with wi-fi or cable. If possbile can you show me how to import or port the driver for iot 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8da9d0-10ee-b8e6-6c11-16f1faf8a630
* Version Independent ID: e45ebd71-6334-7dd6-87a2-933210996f4c
* Content: [Hardware Compatbility List - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist)
* Content Source: [windows-iotcore/learn-about-hardware/HardwareCompatList.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/HardwareCompatList.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @rtarta, as we say in that doc, it's not an exhaustive list. Since this seems out of scope for our documentation, I encourage you to post this on our MSDN forums, here: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT 

We have a staff that monitors these forums.
