### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by siroda** [MicrosoftDocs/windows-iotcore-docs#890]
AAEON Up Squared

broken link: http://www.up-board.org/upsquared/specifications-up2/
correct to: https://up-board.org/upsquared/specifications/

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 257dc32b-f302-db2a-2571-8f217007d893
* Version Independent ID: 92b2f238-f621-3feb-5b5b-07aed095b115
* Content: [Suggested Prototype Boards - Windows IoT](https://docs.microsoft.com/it-it/windows/iot-core/tutorials/quickstarter/prototypeboards)
* Content Source: [windows-iotcore/tutorials/quickstarter/PrototypeBoards.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/quickstarter/PrototypeBoards.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Thanks @siroda! Feel free to submit a pull request directly next time :)
