### ISSUE TITLE
CheckNetIsolation.exe LoopbackExempt -is -n=<MyApp> working after reboot

### ISSUE THREAD

**Issue by asrini777** [MicrosoftDocs/windows-iotcore-docs#909]
Above command is working fine until unless we reboot the system. Is there any way to skip the reboot of system?

**Comment by asrini777** [comment]
Hi @saraclay,

I followed below link
https://docs.microsoft.com/en-us/previous-versions/windows/apps/dn640582(v=win.10)

Thanks,
Srini

**Comment by saraclay** [comment]
Hi @asrini777, your question might be answered quicker via our MSDN forums, here: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT 

Please make sure to include the link to the doc. The doc you linked to is not a doc on this repository.
