### ISSUE TITLE
Securing IoT Core

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/windows-iotcore-docs#918]
Would be nice to have more detail here about how to disable WinRM/Portal/SSH etc.  Default setups have a bunch of unnecessary services running on them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79e5c09a-9c7e-29c1-2b0a-3cb7d3dfeb5a
* Version Independent ID: e4676c9f-a210-fd4a-e338-7cdc873696c8
* Content: [Building Secure Devices with Windows 10 IoT Core - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/buildingsecuredevices)
* Content Source: [windows-iotcore/secure-your-device/BuildingSecureDevices.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/secure-your-device/BuildingSecureDevices.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Thanks @pilcherd. I will pass this on to the owner of these features.
