### ISSUE TITLE
Join a domain

### ISSUE THREAD

**Issue by rjshalom** [MicrosoftDocs/windows-iotcore-docs#934]
Hello,
Is it possible to join a Windows 10 IoT Core device to a Windows Active Directory Domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563b22e3-1c62-eaad-eb29-6f95b01316ba
* Version Independent ID: 385c19a8-007a-f000-496c-0521606cbf9c
* Content: [Overview of Windows 10 IoT Core - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/windows-iot-core)
* Content Source: [windows-iotcore/windows-iot-core.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/windows-iot-core.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @rjshalom, [according to our latest insider release notes](https://docs.microsoft.com/en-us/windows/iot-core/release-notes/currentinsider), this is noted:

Azure Active Directory Authentication Support
The Azure Active Directory Authentication Library does not work on Windows 10 IoT Core.
