### ISSUE TITLE
Can we connect two displays

### ISSUE THREAD

**Issue by senthilkumarchockalingam** [MicrosoftDocs/windows-iotcore-docs#959]
Hello Microsoft,

We are in need of connecting two displays on top of a PC running Windows 10 IOT. One display could be a touch screen(in KIOSK mode) and other one could be a Monitor, both running different applications. We are OK with either Core and Enterprise editions.

Thanks for your help

Best Regards,
Senthil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e02acee3-6daa-e7b9-f0b8-acd860ae5012
* Version Independent ID: 1eb1c5e5-c86d-b1ab-64b6-bbb24fb5bd04
* Content: [Remote display - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/remotedisplay)
* Content Source: [windows-iotcore/manage-your-device/RemoteDisplay.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/manage-your-device/RemoteDisplay.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @senthilkumarchockalingam - this is an inquiry that's a bit more complicated than just the docs :) Could you re-post this on our [MSDN forums](https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT)? We have staff dedicated to helping users on the forums. Thank you!
