### ISSUE TITLE
Does Windows IoT Core support Speech language (ar-sa)?

### ISSUE THREAD

**Issue by xuliujian** [MicrosoftDocs/windows-iotcore-docs#969]
In this document, it says that Windows 10 IoTCore kits now include the language resources for speech language ar-SA. However, when i use the powershell command(IotSettings list speechlanguage) to check the supported language, it does not include ar-SA.
My windows iot core version is 17763.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3038f54-9716-c796-b690-ceee019ac5ca
* Version Independent ID: f9c8f629-d638-5198-b379-bb39a09d00f5
* Content: [Windows 10 IoT Core Language Support - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/multilang)
* Content Source: [windows-iotcore/develop-your-app/MultiLang.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/develop-your-app/MultiLang.md)
* Product: **windows-iot**
* GitHub Login: @msalehmsft
* Microsoft Alias: **msaleh**

**Comment by saraclay** [comment]
@xuliujian we are looking into this. Thank you for your patience.

**Comment by saraclay** [comment]
@xuliujian - while we support ar-SA as a language, it is not supported in speech. The following are supported in speech:

-en-ca
-es-mx
-fr-ca
-en-gb
-es-es
-fr-fr
