### ISSUE TITLE
IoT Core Dashboard installer appears unsigned

### ISSUE THREAD

**Issue by philmea** [MicrosoftDocs/windows-iotcore-docs#970]
Hi,
The installer for the IoT Core Dashboard, setup.exe, appears to not be signed. This blocks installation on many corporate machines and prompts a warning that the installer is potentially harmful. Tested on Windows 10. Product feedback hub was unavailable.

![image](https://user-images.githubusercontent.com/15095922/50503349-43d5f180-0a1b-11e9-968e-1cdc31e4fade.png)

@riverar - GitHub issue to track your feedback. Thanks for the report!

Phil
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9df006b9-0eac-67b8-9f24-e712ec436ec8
* Version Independent ID: 491d3781-235d-1ad5-fff4-9185cbc73984
* Content: [Windows 10 IoT Core Dashboard - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/iotdashboard)
* Content Source: [windows-iotcore/connect-your-device/IoTDashboard.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/connect-your-device/IoTDashboard.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by riverar** [comment]
@saraclay Can you add more information on the closure? Is it fixed?

**Comment by saraclay** [comment]
Apologies @philmea @riverar - we are investigating this. Stay tuned.

**Comment by saraclay** [comment]
Hi @philmea @riverar - this issue has now been resolved.
