### ISSUE TITLE
Stale link

### ISSUE THREAD

**Issue by rsaulat** [MicrosoftDocs/windows-iotcore-docs#971]
The link to "Download the Windows IoT Core Extension for VS Code" in this documentation takes you to Marketplace where you get this message....'This extension is now unpublished from Marketplace. You can choose to uninstall it.'

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dce54db-d545-6d18-e144-e8c1a3021196
* Version Independent ID: fb1acc5b-3e76-595d-c12b-97dad0dcea00
* Content: [Develop an app for your device - Windows IoT](https://docs.microsoft.com/en-gb/windows/iot-core/tutorials/quickstarter/developapp#feedback)
* Content Source: [windows-iotcore/tutorials/quickstarter/DevelopApp.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/quickstarter/DevelopApp.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Thank you. We're fixing this now with a pull request.
