### ISSUE TITLE
Qualcomm Snapdragon

### ISSUE THREAD

**Issue by JeffMushmo** [MicrosoftDocs/windows-iotcore-docs#983]
What is the status of support for USB ethernet adapters being able to run on the Qualcomm Snapdragon 410c?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8da9d0-10ee-b8e6-6c11-16f1faf8a630
* Version Independent ID: e45ebd71-6334-7dd6-87a2-933210996f4c
* Content: [Hardware Compatbility List - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist)
* Content Source: [windows-iotcore/learn-about-hardware/HardwareCompatList.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/HardwareCompatList.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
@JeffMushmo - is there anything specific you're looking for? This already works.

**Comment by JeffMushmo** [comment]
We attempted to use the UGREEN Ethernet Adapter 2.0 here: [https://www.amazon.com/gp/product/B00MYT481C/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1](https://www.amazon.com/gp/product/B00MYT481C/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1)

The error we received was: Unable to reset USB and obtain device descriptor within the Default IoT app that comes with IoT Core.

All other devices were discovered like: Keyboard, Mouse, Touchscreen.

Is there a list of already supported USB-to-Ethernet adapters?

**Comment by saraclay** [comment]
@JeffMushmo we've confirmed that the ASIX AX88772 USB 2.0 Fast Ethernet Adapter works. There are definitely a few others that work, but we have not logged them. When/if you come across another USB-to-Ethernet adapter that works, please submit a PR to update our list :)
